// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: account_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.account.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountLicense : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expires")]
        public ulong Expires
        {
            get => __pbn__Expires.GetValueOrDefault();
            set => __pbn__Expires = value;
        }
        public bool ShouldSerializeExpires() => __pbn__Expires != null;
        public void ResetExpires() => __pbn__Expires = null;
        private ulong? __pbn__Expires;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountHandle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public uint Program { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"region", IsRequired = true)]
        public uint Region { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountReference : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email
        {
            get => __pbn__Email ?? "";
            set => __pbn__Email = value;
        }
        public bool ShouldSerializeEmail() => __pbn__Email != null;
        public void ResetEmail() => __pbn__Email = null;
        private string __pbn__Email;

        [global::ProtoBuf.ProtoMember(3, Name = @"handle")]
        public GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

        [global::ProtoBuf.ProtoMember(5, Name = @"phone_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PhoneNumber
        {
            get => __pbn__PhoneNumber ?? "";
            set => __pbn__PhoneNumber = value;
        }
        public bool ShouldSerializePhoneNumber() => __pbn__PhoneNumber != null;
        public void ResetPhoneNumber() => __pbn__PhoneNumber = null;
        private string __pbn__PhoneNumber;

        [global::ProtoBuf.ProtoMember(10, Name = @"region")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Region
        {
            get => __pbn__Region ?? 0u;
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private uint? __pbn__Region;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Identity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        public AccountId Account { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"game_account")]
        public GameAccountHandle GameAccount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProgramTag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(2, Name = @"tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Tag
        {
            get => __pbn__Tag.GetValueOrDefault();
            set => __pbn__Tag = value;
        }
        public bool ShouldSerializeTag() => __pbn__Tag != null;
        public void ResetTag() => __pbn__Tag = null;
        private uint? __pbn__Tag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionTag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"region", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Region
        {
            get => __pbn__Region.GetValueOrDefault();
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private uint? __pbn__Region;

        [global::ProtoBuf.ProtoMember(2, Name = @"tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Tag
        {
            get => __pbn__Tag.GetValueOrDefault();
            set => __pbn__Tag = value;
        }
        public bool ShouldSerializeTag() => __pbn__Tag != null;
        public void ResetTag() => __pbn__Tag = null;
        private uint? __pbn__Tag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountFieldTags : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"account_level_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint AccountLevelInfoTag
        {
            get => __pbn__AccountLevelInfoTag.GetValueOrDefault();
            set => __pbn__AccountLevelInfoTag = value;
        }
        public bool ShouldSerializeAccountLevelInfoTag() => __pbn__AccountLevelInfoTag != null;
        public void ResetAccountLevelInfoTag() => __pbn__AccountLevelInfoTag = null;
        private uint? __pbn__AccountLevelInfoTag;

        [global::ProtoBuf.ProtoMember(3, Name = @"privacy_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint PrivacyInfoTag
        {
            get => __pbn__PrivacyInfoTag.GetValueOrDefault();
            set => __pbn__PrivacyInfoTag = value;
        }
        public bool ShouldSerializePrivacyInfoTag() => __pbn__PrivacyInfoTag != null;
        public void ResetPrivacyInfoTag() => __pbn__PrivacyInfoTag = null;
        private uint? __pbn__PrivacyInfoTag;

        [global::ProtoBuf.ProtoMember(4, Name = @"parental_control_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint ParentalControlInfoTag
        {
            get => __pbn__ParentalControlInfoTag.GetValueOrDefault();
            set => __pbn__ParentalControlInfoTag = value;
        }
        public bool ShouldSerializeParentalControlInfoTag() => __pbn__ParentalControlInfoTag != null;
        public void ResetParentalControlInfoTag() => __pbn__ParentalControlInfoTag = null;
        private uint? __pbn__ParentalControlInfoTag;

        [global::ProtoBuf.ProtoMember(7, Name = @"game_level_info_tags")]
        public global::System.Collections.Generic.List<ProgramTag> GameLevelInfoTags { get; } = new global::System.Collections.Generic.List<ProgramTag>();

        [global::ProtoBuf.ProtoMember(9, Name = @"game_status_tags")]
        public global::System.Collections.Generic.List<ProgramTag> GameStatusTags { get; } = new global::System.Collections.Generic.List<ProgramTag>();

        [global::ProtoBuf.ProtoMember(11, Name = @"game_account_tags")]
        public global::System.Collections.Generic.List<RegionTag> GameAccountTags { get; } = new global::System.Collections.Generic.List<RegionTag>();

        [global::ProtoBuf.ProtoMember(12, Name = @"security_status_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint SecurityStatusTag
        {
            get => __pbn__SecurityStatusTag.GetValueOrDefault();
            set => __pbn__SecurityStatusTag = value;
        }
        public bool ShouldSerializeSecurityStatusTag() => __pbn__SecurityStatusTag != null;
        public void ResetSecurityStatusTag() => __pbn__SecurityStatusTag = null;
        private uint? __pbn__SecurityStatusTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountFieldTags : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"game_level_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint GameLevelInfoTag
        {
            get => __pbn__GameLevelInfoTag.GetValueOrDefault();
            set => __pbn__GameLevelInfoTag = value;
        }
        public bool ShouldSerializeGameLevelInfoTag() => __pbn__GameLevelInfoTag != null;
        public void ResetGameLevelInfoTag() => __pbn__GameLevelInfoTag = null;
        private uint? __pbn__GameLevelInfoTag;

        [global::ProtoBuf.ProtoMember(3, Name = @"game_time_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint GameTimeInfoTag
        {
            get => __pbn__GameTimeInfoTag.GetValueOrDefault();
            set => __pbn__GameTimeInfoTag = value;
        }
        public bool ShouldSerializeGameTimeInfoTag() => __pbn__GameTimeInfoTag != null;
        public void ResetGameTimeInfoTag() => __pbn__GameTimeInfoTag = null;
        private uint? __pbn__GameTimeInfoTag;

        [global::ProtoBuf.ProtoMember(4, Name = @"game_status_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint GameStatusTag
        {
            get => __pbn__GameStatusTag.GetValueOrDefault();
            set => __pbn__GameStatusTag = value;
        }
        public bool ShouldSerializeGameStatusTag() => __pbn__GameStatusTag != null;
        public void ResetGameStatusTag() => __pbn__GameStatusTag = null;
        private uint? __pbn__GameStatusTag;

        [global::ProtoBuf.ProtoMember(5, Name = @"raf_info_tag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint RafInfoTag
        {
            get => __pbn__RafInfoTag.GetValueOrDefault();
            set => __pbn__RafInfoTag = value;
        }
        public bool ShouldSerializeRafInfoTag() => __pbn__RafInfoTag != null;
        public void ResetRafInfoTag() => __pbn__RafInfoTag = null;
        private uint? __pbn__RafInfoTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountFieldOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"all_fields")]
        public bool AllFields
        {
            get => __pbn__AllFields.GetValueOrDefault();
            set => __pbn__AllFields = value;
        }
        public bool ShouldSerializeAllFields() => __pbn__AllFields != null;
        public void ResetAllFields() => __pbn__AllFields = null;
        private bool? __pbn__AllFields;

        [global::ProtoBuf.ProtoMember(2, Name = @"field_account_level_info")]
        public bool FieldAccountLevelInfo
        {
            get => __pbn__FieldAccountLevelInfo.GetValueOrDefault();
            set => __pbn__FieldAccountLevelInfo = value;
        }
        public bool ShouldSerializeFieldAccountLevelInfo() => __pbn__FieldAccountLevelInfo != null;
        public void ResetFieldAccountLevelInfo() => __pbn__FieldAccountLevelInfo = null;
        private bool? __pbn__FieldAccountLevelInfo;

        [global::ProtoBuf.ProtoMember(3, Name = @"field_privacy_info")]
        public bool FieldPrivacyInfo
        {
            get => __pbn__FieldPrivacyInfo.GetValueOrDefault();
            set => __pbn__FieldPrivacyInfo = value;
        }
        public bool ShouldSerializeFieldPrivacyInfo() => __pbn__FieldPrivacyInfo != null;
        public void ResetFieldPrivacyInfo() => __pbn__FieldPrivacyInfo = null;
        private bool? __pbn__FieldPrivacyInfo;

        [global::ProtoBuf.ProtoMember(4, Name = @"field_parental_control_info")]
        public bool FieldParentalControlInfo
        {
            get => __pbn__FieldParentalControlInfo.GetValueOrDefault();
            set => __pbn__FieldParentalControlInfo = value;
        }
        public bool ShouldSerializeFieldParentalControlInfo() => __pbn__FieldParentalControlInfo != null;
        public void ResetFieldParentalControlInfo() => __pbn__FieldParentalControlInfo = null;
        private bool? __pbn__FieldParentalControlInfo;

        [global::ProtoBuf.ProtoMember(6, Name = @"field_game_level_info")]
        public bool FieldGameLevelInfo
        {
            get => __pbn__FieldGameLevelInfo.GetValueOrDefault();
            set => __pbn__FieldGameLevelInfo = value;
        }
        public bool ShouldSerializeFieldGameLevelInfo() => __pbn__FieldGameLevelInfo != null;
        public void ResetFieldGameLevelInfo() => __pbn__FieldGameLevelInfo = null;
        private bool? __pbn__FieldGameLevelInfo;

        [global::ProtoBuf.ProtoMember(7, Name = @"field_game_status")]
        public bool FieldGameStatus
        {
            get => __pbn__FieldGameStatus.GetValueOrDefault();
            set => __pbn__FieldGameStatus = value;
        }
        public bool ShouldSerializeFieldGameStatus() => __pbn__FieldGameStatus != null;
        public void ResetFieldGameStatus() => __pbn__FieldGameStatus = null;
        private bool? __pbn__FieldGameStatus;

        [global::ProtoBuf.ProtoMember(8, Name = @"field_game_accounts")]
        public bool FieldGameAccounts
        {
            get => __pbn__FieldGameAccounts.GetValueOrDefault();
            set => __pbn__FieldGameAccounts = value;
        }
        public bool ShouldSerializeFieldGameAccounts() => __pbn__FieldGameAccounts != null;
        public void ResetFieldGameAccounts() => __pbn__FieldGameAccounts = null;
        private bool? __pbn__FieldGameAccounts;

        [global::ProtoBuf.ProtoMember(9, Name = @"field_security_status")]
        public bool FieldSecurityStatus
        {
            get => __pbn__FieldSecurityStatus.GetValueOrDefault();
            set => __pbn__FieldSecurityStatus = value;
        }
        public bool ShouldSerializeFieldSecurityStatus() => __pbn__FieldSecurityStatus != null;
        public void ResetFieldSecurityStatus() => __pbn__FieldSecurityStatus = null;
        private bool? __pbn__FieldSecurityStatus;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountFieldOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"all_fields")]
        public bool AllFields
        {
            get => __pbn__AllFields.GetValueOrDefault();
            set => __pbn__AllFields = value;
        }
        public bool ShouldSerializeAllFields() => __pbn__AllFields != null;
        public void ResetAllFields() => __pbn__AllFields = null;
        private bool? __pbn__AllFields;

        [global::ProtoBuf.ProtoMember(2, Name = @"field_game_level_info")]
        public bool FieldGameLevelInfo
        {
            get => __pbn__FieldGameLevelInfo.GetValueOrDefault();
            set => __pbn__FieldGameLevelInfo = value;
        }
        public bool ShouldSerializeFieldGameLevelInfo() => __pbn__FieldGameLevelInfo != null;
        public void ResetFieldGameLevelInfo() => __pbn__FieldGameLevelInfo = null;
        private bool? __pbn__FieldGameLevelInfo;

        [global::ProtoBuf.ProtoMember(3, Name = @"field_game_time_info")]
        public bool FieldGameTimeInfo
        {
            get => __pbn__FieldGameTimeInfo.GetValueOrDefault();
            set => __pbn__FieldGameTimeInfo = value;
        }
        public bool ShouldSerializeFieldGameTimeInfo() => __pbn__FieldGameTimeInfo != null;
        public void ResetFieldGameTimeInfo() => __pbn__FieldGameTimeInfo = null;
        private bool? __pbn__FieldGameTimeInfo;

        [global::ProtoBuf.ProtoMember(4, Name = @"field_game_status")]
        public bool FieldGameStatus
        {
            get => __pbn__FieldGameStatus.GetValueOrDefault();
            set => __pbn__FieldGameStatus = value;
        }
        public bool ShouldSerializeFieldGameStatus() => __pbn__FieldGameStatus != null;
        public void ResetFieldGameStatus() => __pbn__FieldGameStatus = null;
        private bool? __pbn__FieldGameStatus;

        [global::ProtoBuf.ProtoMember(5, Name = @"field_raf_info")]
        public bool FieldRafInfo
        {
            get => __pbn__FieldRafInfo.GetValueOrDefault();
            set => __pbn__FieldRafInfo = value;
        }
        public bool ShouldSerializeFieldRafInfo() => __pbn__FieldRafInfo != null;
        public void ResetFieldRafInfo() => __pbn__FieldRafInfo = null;
        private bool? __pbn__FieldRafInfo;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscriberReference : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong ObjectId
        {
            get => __pbn__ObjectId ?? 0ul;
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_id")]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"account_options")]
        public AccountFieldOptions AccountOptions { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"account_tags")]
        public AccountFieldTags AccountTags { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"game_account_options")]
        public GameAccountFieldOptions GameAccountOptions { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"game_account_tags")]
        public GameAccountFieldTags GameAccountTags { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"subscriber_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong SubscriberId
        {
            get => __pbn__SubscriberId ?? 0ul;
            set => __pbn__SubscriberId = value;
        }
        public bool ShouldSerializeSubscriberId() => __pbn__SubscriberId != null;
        public void ResetSubscriberId() => __pbn__SubscriberId = null;
        private ulong? __pbn__SubscriberId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountLevelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"licenses")]
        public global::System.Collections.Generic.List<AccountLicense> Licenses { get; } = new global::System.Collections.Generic.List<AccountLicense>();

        [global::ProtoBuf.ProtoMember(4, Name = @"default_currency", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint DefaultCurrency
        {
            get => __pbn__DefaultCurrency.GetValueOrDefault();
            set => __pbn__DefaultCurrency = value;
        }
        public bool ShouldSerializeDefaultCurrency() => __pbn__DefaultCurrency != null;
        public void ResetDefaultCurrency() => __pbn__DefaultCurrency = null;
        private uint? __pbn__DefaultCurrency;

        [global::ProtoBuf.ProtoMember(5, Name = @"country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Country
        {
            get => __pbn__Country ?? "";
            set => __pbn__Country = value;
        }
        public bool ShouldSerializeCountry() => __pbn__Country != null;
        public void ResetCountry() => __pbn__Country = null;
        private string __pbn__Country;

        [global::ProtoBuf.ProtoMember(6, Name = @"preferred_region")]
        public uint PreferredRegion
        {
            get => __pbn__PreferredRegion.GetValueOrDefault();
            set => __pbn__PreferredRegion = value;
        }
        public bool ShouldSerializePreferredRegion() => __pbn__PreferredRegion != null;
        public void ResetPreferredRegion() => __pbn__PreferredRegion = null;
        private uint? __pbn__PreferredRegion;

        [global::ProtoBuf.ProtoMember(7, Name = @"full_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FullName
        {
            get => __pbn__FullName ?? "";
            set => __pbn__FullName = value;
        }
        public bool ShouldSerializeFullName() => __pbn__FullName != null;
        public void ResetFullName() => __pbn__FullName = null;
        private string __pbn__FullName;

        [global::ProtoBuf.ProtoMember(8, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

        [global::ProtoBuf.ProtoMember(9, Name = @"muted")]
        public bool Muted
        {
            get => __pbn__Muted.GetValueOrDefault();
            set => __pbn__Muted = value;
        }
        public bool ShouldSerializeMuted() => __pbn__Muted != null;
        public void ResetMuted() => __pbn__Muted = null;
        private bool? __pbn__Muted;

        [global::ProtoBuf.ProtoMember(10, Name = @"manual_review")]
        public bool ManualReview
        {
            get => __pbn__ManualReview.GetValueOrDefault();
            set => __pbn__ManualReview = value;
        }
        public bool ShouldSerializeManualReview() => __pbn__ManualReview != null;
        public void ResetManualReview() => __pbn__ManualReview = null;
        private bool? __pbn__ManualReview;

        [global::ProtoBuf.ProtoMember(11, Name = @"account_paid_any")]
        public bool AccountPaidAny
        {
            get => __pbn__AccountPaidAny.GetValueOrDefault();
            set => __pbn__AccountPaidAny = value;
        }
        public bool ShouldSerializeAccountPaidAny() => __pbn__AccountPaidAny != null;
        public void ResetAccountPaidAny() => __pbn__AccountPaidAny = null;
        private bool? __pbn__AccountPaidAny;

        [global::ProtoBuf.ProtoMember(12, Name = @"identity_check_status")]
        [global::System.ComponentModel.DefaultValue(IdentityVerificationStatus.IdentNoData)]
        public IdentityVerificationStatus IdentityCheckStatus
        {
            get => __pbn__IdentityCheckStatus ?? IdentityVerificationStatus.IdentNoData;
            set => __pbn__IdentityCheckStatus = value;
        }
        public bool ShouldSerializeIdentityCheckStatus() => __pbn__IdentityCheckStatus != null;
        public void ResetIdentityCheckStatus() => __pbn__IdentityCheckStatus = null;
        private IdentityVerificationStatus? __pbn__IdentityCheckStatus;

        [global::ProtoBuf.ProtoMember(13, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email
        {
            get => __pbn__Email ?? "";
            set => __pbn__Email = value;
        }
        public bool ShouldSerializeEmail() => __pbn__Email != null;
        public void ResetEmail() => __pbn__Email = null;
        private string __pbn__Email;

        [global::ProtoBuf.ProtoMember(14, Name = @"headless_account")]
        public bool HeadlessAccount
        {
            get => __pbn__HeadlessAccount.GetValueOrDefault();
            set => __pbn__HeadlessAccount = value;
        }
        public bool ShouldSerializeHeadlessAccount() => __pbn__HeadlessAccount != null;
        public void ResetHeadlessAccount() => __pbn__HeadlessAccount = null;
        private bool? __pbn__HeadlessAccount;

        [global::ProtoBuf.ProtoMember(15, Name = @"test_account")]
        public bool TestAccount
        {
            get => __pbn__TestAccount.GetValueOrDefault();
            set => __pbn__TestAccount = value;
        }
        public bool ShouldSerializeTestAccount() => __pbn__TestAccount != null;
        public void ResetTestAccount() => __pbn__TestAccount = null;
        private bool? __pbn__TestAccount;

        [global::ProtoBuf.ProtoMember(17, Name = @"is_sms_protected")]
        public bool IsSmsProtected
        {
            get => __pbn__IsSmsProtected.GetValueOrDefault();
            set => __pbn__IsSmsProtected = value;
        }
        public bool ShouldSerializeIsSmsProtected() => __pbn__IsSmsProtected != null;
        public void ResetIsSmsProtected() => __pbn__IsSmsProtected = null;
        private bool? __pbn__IsSmsProtected;

        [global::ProtoBuf.ProtoMember(18, Name = @"ratings_board_minimum_age")]
        public uint RatingsBoardMinimumAge
        {
            get => __pbn__RatingsBoardMinimumAge.GetValueOrDefault();
            set => __pbn__RatingsBoardMinimumAge = value;
        }
        public bool ShouldSerializeRatingsBoardMinimumAge() => __pbn__RatingsBoardMinimumAge != null;
        public void ResetRatingsBoardMinimumAge() => __pbn__RatingsBoardMinimumAge = null;
        private uint? __pbn__RatingsBoardMinimumAge;

        [global::ProtoBuf.ProtoMember(19, Name = @"phone_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PhoneNumber
        {
            get => __pbn__PhoneNumber ?? "";
            set => __pbn__PhoneNumber = value;
        }
        public bool ShouldSerializePhoneNumber() => __pbn__PhoneNumber != null;
        public void ResetPhoneNumber() => __pbn__PhoneNumber = null;
        private string __pbn__PhoneNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrivacyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"is_using_rid")]
        public bool IsUsingRid
        {
            get => __pbn__IsUsingRid.GetValueOrDefault();
            set => __pbn__IsUsingRid = value;
        }
        public bool ShouldSerializeIsUsingRid() => __pbn__IsUsingRid != null;
        public void ResetIsUsingRid() => __pbn__IsUsingRid = null;
        private bool? __pbn__IsUsingRid;

        [global::ProtoBuf.ProtoMember(4, Name = @"is_visible_for_view_friends")]
        public bool IsVisibleForViewFriends
        {
            get => __pbn__IsVisibleForViewFriends.GetValueOrDefault();
            set => __pbn__IsVisibleForViewFriends = value;
        }
        public bool ShouldSerializeIsVisibleForViewFriends() => __pbn__IsVisibleForViewFriends != null;
        public void ResetIsVisibleForViewFriends() => __pbn__IsVisibleForViewFriends = null;
        private bool? __pbn__IsVisibleForViewFriends;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_hidden_from_friend_finder")]
        public bool IsHiddenFromFriendFinder
        {
            get => __pbn__IsHiddenFromFriendFinder.GetValueOrDefault();
            set => __pbn__IsHiddenFromFriendFinder = value;
        }
        public bool ShouldSerializeIsHiddenFromFriendFinder() => __pbn__IsHiddenFromFriendFinder != null;
        public void ResetIsHiddenFromFriendFinder() => __pbn__IsHiddenFromFriendFinder = null;
        private bool? __pbn__IsHiddenFromFriendFinder;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(GameInfoPrivacy.PrivacyFriends)]
        public GameInfoPrivacy game_info_privacy
        {
            get => __pbn__game_info_privacy ?? GameInfoPrivacy.PrivacyFriends;
            set => __pbn__game_info_privacy = value;
        }
        public bool ShouldSerializegame_info_privacy() => __pbn__game_info_privacy != null;
        public void Resetgame_info_privacy() => __pbn__game_info_privacy = null;
        private GameInfoPrivacy? __pbn__game_info_privacy;

        [global::ProtoBuf.ProtoMember(7, Name = @"only_allow_friend_whispers")]
        public bool OnlyAllowFriendWhispers
        {
            get => __pbn__OnlyAllowFriendWhispers.GetValueOrDefault();
            set => __pbn__OnlyAllowFriendWhispers = value;
        }
        public bool ShouldSerializeOnlyAllowFriendWhispers() => __pbn__OnlyAllowFriendWhispers != null;
        public void ResetOnlyAllowFriendWhispers() => __pbn__OnlyAllowFriendWhispers = null;
        private bool? __pbn__OnlyAllowFriendWhispers;

        [global::ProtoBuf.ProtoContract()]
        public enum GameInfoPrivacy
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_ME")]
            PrivacyMe = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_FRIENDS")]
            PrivacyFriends = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_EVERYONE")]
            PrivacyEveryone = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ParentalControlInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"timezone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Timezone
        {
            get => __pbn__Timezone ?? "";
            set => __pbn__Timezone = value;
        }
        public bool ShouldSerializeTimezone() => __pbn__Timezone != null;
        public void ResetTimezone() => __pbn__Timezone = null;
        private string __pbn__Timezone;

        [global::ProtoBuf.ProtoMember(4, Name = @"minutes_per_day")]
        public uint MinutesPerDay
        {
            get => __pbn__MinutesPerDay.GetValueOrDefault();
            set => __pbn__MinutesPerDay = value;
        }
        public bool ShouldSerializeMinutesPerDay() => __pbn__MinutesPerDay != null;
        public void ResetMinutesPerDay() => __pbn__MinutesPerDay = null;
        private uint? __pbn__MinutesPerDay;

        [global::ProtoBuf.ProtoMember(5, Name = @"minutes_per_week")]
        public uint MinutesPerWeek
        {
            get => __pbn__MinutesPerWeek.GetValueOrDefault();
            set => __pbn__MinutesPerWeek = value;
        }
        public bool ShouldSerializeMinutesPerWeek() => __pbn__MinutesPerWeek != null;
        public void ResetMinutesPerWeek() => __pbn__MinutesPerWeek = null;
        private uint? __pbn__MinutesPerWeek;

        [global::ProtoBuf.ProtoMember(6, Name = @"can_receive_voice")]
        public bool CanReceiveVoice
        {
            get => __pbn__CanReceiveVoice.GetValueOrDefault();
            set => __pbn__CanReceiveVoice = value;
        }
        public bool ShouldSerializeCanReceiveVoice() => __pbn__CanReceiveVoice != null;
        public void ResetCanReceiveVoice() => __pbn__CanReceiveVoice = null;
        private bool? __pbn__CanReceiveVoice;

        [global::ProtoBuf.ProtoMember(7, Name = @"can_send_voice")]
        public bool CanSendVoice
        {
            get => __pbn__CanSendVoice.GetValueOrDefault();
            set => __pbn__CanSendVoice = value;
        }
        public bool ShouldSerializeCanSendVoice() => __pbn__CanSendVoice != null;
        public void ResetCanSendVoice() => __pbn__CanSendVoice = null;
        private bool? __pbn__CanSendVoice;

        [global::ProtoBuf.ProtoMember(8, Name = @"play_schedule")]
        public bool[] PlaySchedules { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"can_join_group")]
        public bool CanJoinGroup
        {
            get => __pbn__CanJoinGroup.GetValueOrDefault();
            set => __pbn__CanJoinGroup = value;
        }
        public bool ShouldSerializeCanJoinGroup() => __pbn__CanJoinGroup != null;
        public void ResetCanJoinGroup() => __pbn__CanJoinGroup = null;
        private bool? __pbn__CanJoinGroup;

        [global::ProtoBuf.ProtoMember(10, Name = @"can_use_profile")]
        public bool CanUseProfile
        {
            get => __pbn__CanUseProfile.GetValueOrDefault();
            set => __pbn__CanUseProfile = value;
        }
        public bool ShouldSerializeCanUseProfile() => __pbn__CanUseProfile != null;
        public void ResetCanUseProfile() => __pbn__CanUseProfile = null;
        private bool? __pbn__CanUseProfile;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayScheduleRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"play_schedule")]
        public bool[] PlaySchedules { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"timezone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Timezone
        {
            get => __pbn__Timezone ?? "";
            set => __pbn__Timezone = value;
        }
        public bool ShouldSerializeTimezone() => __pbn__Timezone != null;
        public void ResetTimezone() => __pbn__Timezone = null;
        private string __pbn__Timezone;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameLevelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"is_trial")]
        public bool IsTrial
        {
            get => __pbn__IsTrial.GetValueOrDefault();
            set => __pbn__IsTrial = value;
        }
        public bool ShouldSerializeIsTrial() => __pbn__IsTrial != null;
        public void ResetIsTrial() => __pbn__IsTrial = null;
        private bool? __pbn__IsTrial;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_lifetime")]
        public bool IsLifetime
        {
            get => __pbn__IsLifetime.GetValueOrDefault();
            set => __pbn__IsLifetime = value;
        }
        public bool ShouldSerializeIsLifetime() => __pbn__IsLifetime != null;
        public void ResetIsLifetime() => __pbn__IsLifetime = null;
        private bool? __pbn__IsLifetime;

        [global::ProtoBuf.ProtoMember(6, Name = @"is_restricted")]
        public bool IsRestricted
        {
            get => __pbn__IsRestricted.GetValueOrDefault();
            set => __pbn__IsRestricted = value;
        }
        public bool ShouldSerializeIsRestricted() => __pbn__IsRestricted != null;
        public void ResetIsRestricted() => __pbn__IsRestricted = null;
        private bool? __pbn__IsRestricted;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_beta")]
        public bool IsBeta
        {
            get => __pbn__IsBeta.GetValueOrDefault();
            set => __pbn__IsBeta = value;
        }
        public bool ShouldSerializeIsBeta() => __pbn__IsBeta != null;
        public void ResetIsBeta() => __pbn__IsBeta = null;
        private bool? __pbn__IsBeta;

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(9, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(10, Name = @"licenses")]
        public global::System.Collections.Generic.List<AccountLicense> Licenses { get; } = new global::System.Collections.Generic.List<AccountLicense>();

        [global::ProtoBuf.ProtoMember(11, Name = @"realm_permissions")]
        public uint RealmPermissions
        {
            get => __pbn__RealmPermissions.GetValueOrDefault();
            set => __pbn__RealmPermissions = value;
        }
        public bool ShouldSerializeRealmPermissions() => __pbn__RealmPermissions != null;
        public void ResetRealmPermissions() => __pbn__RealmPermissions = null;
        private uint? __pbn__RealmPermissions;

        [global::ProtoBuf.ProtoMember(12, Name = @"last_logout_time_ms")]
        public ulong LastLogoutTimeMs
        {
            get => __pbn__LastLogoutTimeMs.GetValueOrDefault();
            set => __pbn__LastLogoutTimeMs = value;
        }
        public bool ShouldSerializeLastLogoutTimeMs() => __pbn__LastLogoutTimeMs != null;
        public void ResetLastLogoutTimeMs() => __pbn__LastLogoutTimeMs = null;
        private ulong? __pbn__LastLogoutTimeMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameTimeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"is_unlimited_play_time")]
        public bool IsUnlimitedPlayTime
        {
            get => __pbn__IsUnlimitedPlayTime.GetValueOrDefault();
            set => __pbn__IsUnlimitedPlayTime = value;
        }
        public bool ShouldSerializeIsUnlimitedPlayTime() => __pbn__IsUnlimitedPlayTime != null;
        public void ResetIsUnlimitedPlayTime() => __pbn__IsUnlimitedPlayTime = null;
        private bool? __pbn__IsUnlimitedPlayTime;

        [global::ProtoBuf.ProtoMember(5, Name = @"play_time_expires")]
        public ulong PlayTimeExpires
        {
            get => __pbn__PlayTimeExpires.GetValueOrDefault();
            set => __pbn__PlayTimeExpires = value;
        }
        public bool ShouldSerializePlayTimeExpires() => __pbn__PlayTimeExpires != null;
        public void ResetPlayTimeExpires() => __pbn__PlayTimeExpires = null;
        private ulong? __pbn__PlayTimeExpires;

        [global::ProtoBuf.ProtoMember(6, Name = @"is_subscription")]
        public bool IsSubscription
        {
            get => __pbn__IsSubscription.GetValueOrDefault();
            set => __pbn__IsSubscription = value;
        }
        public bool ShouldSerializeIsSubscription() => __pbn__IsSubscription != null;
        public void ResetIsSubscription() => __pbn__IsSubscription = null;
        private bool? __pbn__IsSubscription;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_recurring_subscription")]
        public bool IsRecurringSubscription
        {
            get => __pbn__IsRecurringSubscription.GetValueOrDefault();
            set => __pbn__IsRecurringSubscription = value;
        }
        public bool ShouldSerializeIsRecurringSubscription() => __pbn__IsRecurringSubscription != null;
        public void ResetIsRecurringSubscription() => __pbn__IsRecurringSubscription = null;
        private bool? __pbn__IsRecurringSubscription;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameTimeRemainingInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"minutes_remaining")]
        public uint MinutesRemaining
        {
            get => __pbn__MinutesRemaining.GetValueOrDefault();
            set => __pbn__MinutesRemaining = value;
        }
        public bool ShouldSerializeMinutesRemaining() => __pbn__MinutesRemaining != null;
        public void ResetMinutesRemaining() => __pbn__MinutesRemaining = null;
        private uint? __pbn__MinutesRemaining;

        [global::ProtoBuf.ProtoMember(2, Name = @"parental_daily_minutes_remaining")]
        public uint ParentalDailyMinutesRemaining
        {
            get => __pbn__ParentalDailyMinutesRemaining.GetValueOrDefault();
            set => __pbn__ParentalDailyMinutesRemaining = value;
        }
        public bool ShouldSerializeParentalDailyMinutesRemaining() => __pbn__ParentalDailyMinutesRemaining != null;
        public void ResetParentalDailyMinutesRemaining() => __pbn__ParentalDailyMinutesRemaining = null;
        private uint? __pbn__ParentalDailyMinutesRemaining;

        [global::ProtoBuf.ProtoMember(3, Name = @"parental_weekly_minutes_remaining")]
        public uint ParentalWeeklyMinutesRemaining
        {
            get => __pbn__ParentalWeeklyMinutesRemaining.GetValueOrDefault();
            set => __pbn__ParentalWeeklyMinutesRemaining = value;
        }
        public bool ShouldSerializeParentalWeeklyMinutesRemaining() => __pbn__ParentalWeeklyMinutesRemaining != null;
        public void ResetParentalWeeklyMinutesRemaining() => __pbn__ParentalWeeklyMinutesRemaining = null;
        private uint? __pbn__ParentalWeeklyMinutesRemaining;

        [global::ProtoBuf.ProtoMember(4, Name = @"seconds_remaining_until_kick")]
        [global::System.Obsolete]
        public uint SecondsRemainingUntilKick
        {
            get => __pbn__SecondsRemainingUntilKick.GetValueOrDefault();
            set => __pbn__SecondsRemainingUntilKick = value;
        }
        public bool ShouldSerializeSecondsRemainingUntilKick() => __pbn__SecondsRemainingUntilKick != null;
        public void ResetSecondsRemainingUntilKick() => __pbn__SecondsRemainingUntilKick = null;
        private uint? __pbn__SecondsRemainingUntilKick;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"is_suspended")]
        public bool IsSuspended
        {
            get => __pbn__IsSuspended.GetValueOrDefault();
            set => __pbn__IsSuspended = value;
        }
        public bool ShouldSerializeIsSuspended() => __pbn__IsSuspended != null;
        public void ResetIsSuspended() => __pbn__IsSuspended = null;
        private bool? __pbn__IsSuspended;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_banned")]
        public bool IsBanned
        {
            get => __pbn__IsBanned.GetValueOrDefault();
            set => __pbn__IsBanned = value;
        }
        public bool ShouldSerializeIsBanned() => __pbn__IsBanned != null;
        public void ResetIsBanned() => __pbn__IsBanned = null;
        private bool? __pbn__IsBanned;

        [global::ProtoBuf.ProtoMember(6, Name = @"suspension_expires")]
        public ulong SuspensionExpires
        {
            get => __pbn__SuspensionExpires.GetValueOrDefault();
            set => __pbn__SuspensionExpires = value;
        }
        public bool ShouldSerializeSuspensionExpires() => __pbn__SuspensionExpires != null;
        public void ResetSuspensionExpires() => __pbn__SuspensionExpires = null;
        private ulong? __pbn__SuspensionExpires;

        [global::ProtoBuf.ProtoMember(7, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(8, Name = @"is_locked")]
        public bool IsLocked
        {
            get => __pbn__IsLocked.GetValueOrDefault();
            set => __pbn__IsLocked = value;
        }
        public bool ShouldSerializeIsLocked() => __pbn__IsLocked != null;
        public void ResetIsLocked() => __pbn__IsLocked = null;
        private bool? __pbn__IsLocked;

        [global::ProtoBuf.ProtoMember(9, Name = @"is_bam_unlockable")]
        public bool IsBamUnlockable
        {
            get => __pbn__IsBamUnlockable.GetValueOrDefault();
            set => __pbn__IsBamUnlockable = value;
        }
        public bool ShouldSerializeIsBamUnlockable() => __pbn__IsBamUnlockable != null;
        public void ResetIsBamUnlockable() => __pbn__IsBamUnlockable = null;
        private bool? __pbn__IsBamUnlockable;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RAFInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"raf_info")]
        public byte[] RafInfo
        {
            get => __pbn__RafInfo;
            set => __pbn__RafInfo = value;
        }
        public bool ShouldSerializeRafInfo() => __pbn__RafInfo != null;
        public void ResetRafInfo() => __pbn__RafInfo = null;
        private byte[] __pbn__RafInfo;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameSessionInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"start_time")]
        [global::System.Obsolete]
        public uint StartTime
        {
            get => __pbn__StartTime.GetValueOrDefault();
            set => __pbn__StartTime = value;
        }
        public bool ShouldSerializeStartTime() => __pbn__StartTime != null;
        public void ResetStartTime() => __pbn__StartTime = null;
        private uint? __pbn__StartTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"location")]
        public GameSessionLocation Location { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"has_benefactor")]
        public bool HasBenefactor
        {
            get => __pbn__HasBenefactor.GetValueOrDefault();
            set => __pbn__HasBenefactor = value;
        }
        public bool ShouldSerializeHasBenefactor() => __pbn__HasBenefactor != null;
        public void ResetHasBenefactor() => __pbn__HasBenefactor = null;
        private bool? __pbn__HasBenefactor;

        [global::ProtoBuf.ProtoMember(6, Name = @"is_using_igr")]
        public bool IsUsingIgr
        {
            get => __pbn__IsUsingIgr.GetValueOrDefault();
            set => __pbn__IsUsingIgr = value;
        }
        public bool ShouldSerializeIsUsingIgr() => __pbn__IsUsingIgr != null;
        public void ResetIsUsingIgr() => __pbn__IsUsingIgr = null;
        private bool? __pbn__IsUsingIgr;

        [global::ProtoBuf.ProtoMember(7, Name = @"parental_controls_active")]
        public bool ParentalControlsActive
        {
            get => __pbn__ParentalControlsActive.GetValueOrDefault();
            set => __pbn__ParentalControlsActive = value;
        }
        public bool ShouldSerializeParentalControlsActive() => __pbn__ParentalControlsActive != null;
        public void ResetParentalControlsActive() => __pbn__ParentalControlsActive = null;
        private bool? __pbn__ParentalControlsActive;

        [global::ProtoBuf.ProtoMember(8, Name = @"start_time_sec")]
        public ulong StartTimeSec
        {
            get => __pbn__StartTimeSec.GetValueOrDefault();
            set => __pbn__StartTimeSec = value;
        }
        public bool ShouldSerializeStartTimeSec() => __pbn__StartTimeSec != null;
        public void ResetStartTimeSec() => __pbn__StartTimeSec = null;
        private ulong? __pbn__StartTimeSec;

        [global::ProtoBuf.ProtoMember(9, Name = @"igr_id")]
        public IgrId IgrId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameSessionUpdateInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"cais")]
        public Cais Cais { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameSessionLocation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ip_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IpAddress
        {
            get => __pbn__IpAddress ?? "";
            set => __pbn__IpAddress = value;
        }
        public bool ShouldSerializeIpAddress() => __pbn__IpAddress != null;
        public void ResetIpAddress() => __pbn__IpAddress = null;
        private string __pbn__IpAddress;

        [global::ProtoBuf.ProtoMember(2, Name = @"country")]
        public uint Country
        {
            get => __pbn__Country.GetValueOrDefault();
            set => __pbn__Country = value;
        }
        public bool ShouldSerializeCountry() => __pbn__Country != null;
        public void ResetCountry() => __pbn__Country = null;
        private uint? __pbn__Country;

        [global::ProtoBuf.ProtoMember(3, Name = @"city")]
        [global::System.ComponentModel.DefaultValue("")]
        public string City
        {
            get => __pbn__City ?? "";
            set => __pbn__City = value;
        }
        public bool ShouldSerializeCity() => __pbn__City != null;
        public void ResetCity() => __pbn__City = null;
        private string __pbn__City;

    }

    [global::ProtoBuf.ProtoContract(Name = @"CAIS")]
    public partial class Cais : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"played_minutes")]
        public uint PlayedMinutes
        {
            get => __pbn__PlayedMinutes.GetValueOrDefault();
            set => __pbn__PlayedMinutes = value;
        }
        public bool ShouldSerializePlayedMinutes() => __pbn__PlayedMinutes != null;
        public void ResetPlayedMinutes() => __pbn__PlayedMinutes = null;
        private uint? __pbn__PlayedMinutes;

        [global::ProtoBuf.ProtoMember(2, Name = @"rested_minutes")]
        public uint RestedMinutes
        {
            get => __pbn__RestedMinutes.GetValueOrDefault();
            set => __pbn__RestedMinutes = value;
        }
        public bool ShouldSerializeRestedMinutes() => __pbn__RestedMinutes != null;
        public void ResetRestedMinutes() => __pbn__RestedMinutes = null;
        private uint? __pbn__RestedMinutes;

        [global::ProtoBuf.ProtoMember(3, Name = @"last_heard_time")]
        public ulong LastHeardTime
        {
            get => __pbn__LastHeardTime.GetValueOrDefault();
            set => __pbn__LastHeardTime = value;
        }
        public bool ShouldSerializeLastHeardTime() => __pbn__LastHeardTime != null;
        public void ResetLastHeardTime() => __pbn__LastHeardTime = null;
        private ulong? __pbn__LastHeardTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"region")]
        public uint Region
        {
            get => __pbn__Region.GetValueOrDefault();
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private uint? __pbn__Region;

        [global::ProtoBuf.ProtoMember(4, Name = @"handle")]
        public global::System.Collections.Generic.List<GameAccountHandle> Handles { get; } = new global::System.Collections.Generic.List<GameAccountHandle>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SecurityStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sms_protect_enabled")]
        public bool SmsProtectEnabled
        {
            get => __pbn__SmsProtectEnabled.GetValueOrDefault();
            set => __pbn__SmsProtectEnabled = value;
        }
        public bool ShouldSerializeSmsProtectEnabled() => __pbn__SmsProtectEnabled != null;
        public void ResetSmsProtectEnabled() => __pbn__SmsProtectEnabled = null;
        private bool? __pbn__SmsProtectEnabled;

        [global::ProtoBuf.ProtoMember(2, Name = @"email_verified")]
        public bool EmailVerified
        {
            get => __pbn__EmailVerified.GetValueOrDefault();
            set => __pbn__EmailVerified = value;
        }
        public bool ShouldSerializeEmailVerified() => __pbn__EmailVerified != null;
        public void ResetEmailVerified() => __pbn__EmailVerified = null;
        private bool? __pbn__EmailVerified;

        [global::ProtoBuf.ProtoMember(3, Name = @"authenticator_enabled")]
        public bool AuthenticatorEnabled
        {
            get => __pbn__AuthenticatorEnabled.GetValueOrDefault();
            set => __pbn__AuthenticatorEnabled = value;
        }
        public bool ShouldSerializeAuthenticatorEnabled() => __pbn__AuthenticatorEnabled != null;
        public void ResetAuthenticatorEnabled() => __pbn__AuthenticatorEnabled = null;
        private bool? __pbn__AuthenticatorEnabled;

        [global::ProtoBuf.ProtoMember(4, Name = @"sqa_enabled")]
        public bool SqaEnabled
        {
            get => __pbn__SqaEnabled.GetValueOrDefault();
            set => __pbn__SqaEnabled = value;
        }
        public bool ShouldSerializeSqaEnabled() => __pbn__SqaEnabled != null;
        public void ResetSqaEnabled() => __pbn__SqaEnabled = null;
        private bool? __pbn__SqaEnabled;

        [global::ProtoBuf.ProtoMember(5, Name = @"authenticator_required")]
        public bool AuthenticatorRequired
        {
            get => __pbn__AuthenticatorRequired.GetValueOrDefault();
            set => __pbn__AuthenticatorRequired = value;
        }
        public bool ShouldSerializeAuthenticatorRequired() => __pbn__AuthenticatorRequired != null;
        public void ResetAuthenticatorRequired() => __pbn__AuthenticatorRequired = null;
        private bool? __pbn__AuthenticatorRequired;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_level_info")]
        public AccountLevelInfo AccountLevelInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"privacy_info")]
        public PrivacyInfo PrivacyInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"parental_control_info")]
        public ParentalControlInfo ParentalControlInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"game_level_info")]
        public global::System.Collections.Generic.List<GameLevelInfo> GameLevelInfoes { get; } = new global::System.Collections.Generic.List<GameLevelInfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"game_status")]
        public global::System.Collections.Generic.List<GameStatus> GameStatus { get; } = new global::System.Collections.Generic.List<GameStatus>();

        [global::ProtoBuf.ProtoMember(7, Name = @"game_accounts")]
        public global::System.Collections.Generic.List<GameAccountList> GameAccounts { get; } = new global::System.Collections.Generic.List<GameAccountList>();

        [global::ProtoBuf.ProtoMember(8, Name = @"security_status")]
        public SecurityStatus SecurityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"government_curfew")]
        public PlayScheduleRestriction GovernmentCurfew { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountStateTagged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_state")]
        public AccountState AccountState { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"account_tags")]
        public AccountFieldTags AccountTags { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_level_info")]
        public GameLevelInfo GameLevelInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"game_time_info")]
        public GameTimeInfo GameTimeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"game_status")]
        public GameStatus GameStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"raf_info")]
        public RAFInfo RafInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountStateTagged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_account_state")]
        public GameAccountState GameAccountState { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"game_account_tags")]
        public GameAccountFieldTags GameAccountTags { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthorizedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Data
        {
            get => __pbn__Data ?? "";
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private string __pbn__Data;

        [global::ProtoBuf.ProtoMember(2, Name = @"license")]
        public uint[] Licenses { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IgrId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_account")]
        public GameAccountHandle GameAccount
        {
            get => __pbn__type.Is(1) ? ((GameAccountHandle)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
        }
        public bool ShouldSerializeGameAccount() => __pbn__type.Is(1);
        public void ResetGameAccount() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__type, 1);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"external_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint ExternalId
        {
            get => __pbn__type.Is(2) ? __pbn__type.UInt32 : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeExternalId() => __pbn__type.Is(2);
        public void ResetExternalId() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__type, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid
        {
            get => __pbn__type.Is(3) ? ((string)__pbn__type.Object) : "";
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
        }
        public bool ShouldSerializeUuid() => __pbn__type.Is(3);
        public void ResetUuid() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__type, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IgrAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"client_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientAddress
        {
            get => __pbn__ClientAddress ?? "";
            set => __pbn__ClientAddress = value;
        }
        public bool ShouldSerializeClientAddress() => __pbn__ClientAddress != null;
        public void ResetClientAddress() => __pbn__ClientAddress = null;
        private string __pbn__ClientAddress;

        [global::ProtoBuf.ProtoMember(2, Name = @"region")]
        public uint Region
        {
            get => __pbn__Region.GetValueOrDefault();
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private uint? __pbn__Region;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum IdentityVerificationStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_NO_DATA")]
        IdentNoData = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_PENDING")]
        IdentPending = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_OVER_18")]
        IdentOver18 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_UNDER_18")]
        IdentUnder18 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_FAILED")]
        IdentFailed = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_SUCCESS")]
        IdentSuccess = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_SUCC_MNL")]
        IdentSuccMnl = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"IDENT_UNKNOWN")]
        IdentUnknown = 7,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
