// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: channel_membership_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.channel.v2.membership
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public global::bgs.protocol.channel.v1.ChannelMembershipState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public global::bgs.protocol.channel.v1.ChannelMembershipState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelAddedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subscriber_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle SubscriberId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"membership")]
        public global::bgs.protocol.channel.v1.ChannelDescription Membership { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelRemovedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subscriber_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle SubscriberId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"channel_id")]
        public global::bgs.protocol.channel.v1.ChannelId ChannelId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue(global::bgs.protocol.channel.v2.ChannelRemovedReason.ChannelRemovedReasonMemberLeft)]
        public global::bgs.protocol.channel.v2.ChannelRemovedReason Reason
        {
            get => __pbn__Reason ?? global::bgs.protocol.channel.v2.ChannelRemovedReason.ChannelRemovedReasonMemberLeft;
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private global::bgs.protocol.channel.v2.ChannelRemovedReason? __pbn__Reason;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReceivedInvitationAddedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subscriber_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle SubscriberId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation")]
        public global::bgs.protocol.channel.v1.ChannelInvitation Invitation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReceivedInvitationRemovedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subscriber_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle SubscriberId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InvitationId
        {
            get => __pbn__InvitationId.GetValueOrDefault();
            set => __pbn__InvitationId = value;
        }
        public bool ShouldSerializeInvitationId() => __pbn__InvitationId != null;
        public void ResetInvitationId() => __pbn__InvitationId = null;
        private ulong? __pbn__InvitationId;

        [global::ProtoBuf.ProtoMember(4, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue(global::bgs.protocol.InvitationRemovedReason.InvitationRemovedReasonAccepted)]
        public global::bgs.protocol.InvitationRemovedReason Reason
        {
            get => __pbn__Reason ?? global::bgs.protocol.InvitationRemovedReason.InvitationRemovedReasonAccepted;
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private global::bgs.protocol.InvitationRemovedReason? __pbn__Reason;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
