// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: channel_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.channel.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListChannelsOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_index")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint StartIndex
        {
            get => __pbn__StartIndex ?? 0u;
            set => __pbn__StartIndex = value;
        }
        public bool ShouldSerializeStartIndex() => __pbn__StartIndex != null;
        public void ResetStartIndex() => __pbn__StartIndex = null;
        private uint? __pbn__StartIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"max_results")]
        [global::System.ComponentModel.DefaultValue(16u)]
        public uint MaxResults
        {
            get => __pbn__MaxResults ?? 16u;
            set => __pbn__MaxResults = value;
        }
        public bool ShouldSerializeMaxResults() => __pbn__MaxResults != null;
        public void ResetMaxResults() => __pbn__MaxResults = null;
        private uint? __pbn__MaxResults;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(5, Name = @"locale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Locale
        {
            get => __pbn__Locale.GetValueOrDefault();
            set => __pbn__Locale = value;
        }
        public bool ShouldSerializeLocale() => __pbn__Locale != null;
        public void ResetLocale() => __pbn__Locale = null;
        private uint? __pbn__Locale;

        [global::ProtoBuf.ProtoMember(6, Name = @"capacity_full")]
        public uint CapacityFull
        {
            get => __pbn__CapacityFull.GetValueOrDefault();
            set => __pbn__CapacityFull = value;
        }
        public bool ShouldSerializeCapacityFull() => __pbn__CapacityFull != null;
        public void ResetCapacityFull() => __pbn__CapacityFull = null;
        private uint? __pbn__CapacityFull;

        [global::ProtoBuf.ProtoMember(7, Name = @"attribute_filter", IsRequired = true)]
        public global::bgs.protocol.v2.AttributeFilter AttributeFilter { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"channel_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChannelType
        {
            get => __pbn__ChannelType ?? "";
            set => __pbn__ChannelType = value;
        }
        public bool ShouldSerializeChannelType() => __pbn__ChannelType != null;
        public void ResetChannelType() => __pbn__ChannelType = null;
        private string __pbn__ChannelType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id", IsRequired = true)]
        public global::bgs.protocol.EntityId ChannelId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"current_members")]
        public uint CurrentMembers
        {
            get => __pbn__CurrentMembers.GetValueOrDefault();
            set => __pbn__CurrentMembers = value;
        }
        public bool ShouldSerializeCurrentMembers() => __pbn__CurrentMembers != null;
        public void ResetCurrentMembers() => __pbn__CurrentMembers = null;
        private uint? __pbn__CurrentMembers;

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public ChannelState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"description", IsRequired = true)]
        public ChannelDescription Description { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"member")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_members")]
        public uint MaxMembers
        {
            get => __pbn__MaxMembers.GetValueOrDefault();
            set => __pbn__MaxMembers = value;
        }
        public bool ShouldSerializeMaxMembers() => __pbn__MaxMembers != null;
        public void ResetMaxMembers() => __pbn__MaxMembers = null;
        private uint? __pbn__MaxMembers;

        [global::ProtoBuf.ProtoMember(2, Name = @"min_members")]
        public uint MinMembers
        {
            get => __pbn__MinMembers.GetValueOrDefault();
            set => __pbn__MinMembers = value;
        }
        public bool ShouldSerializeMinMembers() => __pbn__MinMembers != null;
        public void ResetMinMembers() => __pbn__MinMembers = null;
        private uint? __pbn__MinMembers;

        [global::ProtoBuf.ProtoMember(3, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(4, Name = @"invitation")]
        public global::System.Collections.Generic.List<global::bgs.protocol.Invitation> Invitations { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.Invitation>();

        [global::ProtoBuf.ProtoMember(6, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(PrivacyLevel.PrivacyLevelOpen)]
        public PrivacyLevel privacy_level
        {
            get => __pbn__privacy_level ?? PrivacyLevel.PrivacyLevelOpen;
            set => __pbn__privacy_level = value;
        }
        public bool ShouldSerializeprivacy_level() => __pbn__privacy_level != null;
        public void Resetprivacy_level() => __pbn__privacy_level = null;
        private PrivacyLevel? __pbn__privacy_level;

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(10, Name = @"channel_type")]
        [global::System.ComponentModel.DefaultValue(@"default")]
        public string ChannelType
        {
            get => __pbn__ChannelType ?? @"default";
            set => __pbn__ChannelType = value;
        }
        public bool ShouldSerializeChannelType() => __pbn__ChannelType != null;
        public void ResetChannelType() => __pbn__ChannelType = null;
        private string __pbn__ChannelType;

        [global::ProtoBuf.ProtoMember(11, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Program
        {
            get => __pbn__Program ?? 0u;
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(13, Name = @"subscribe_to_presence")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool SubscribeToPresence
        {
            get => __pbn__SubscribeToPresence ?? true;
            set => __pbn__SubscribeToPresence = value;
        }
        public bool ShouldSerializeSubscribeToPresence() => __pbn__SubscribeToPresence != null;
        public void ResetSubscribeToPresence() => __pbn__SubscribeToPresence = null;
        private bool? __pbn__SubscribeToPresence;

        [global::ProtoBuf.ProtoContract()]
        public enum PrivacyLevel
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_LEVEL_OPEN")]
            PrivacyLevelOpen = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND")]
            PrivacyLevelOpenInvitationAndFriend = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_LEVEL_OPEN_INVITATION")]
            PrivacyLevelOpenInvitation = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PRIVACY_LEVEL_CLOSED")]
            PrivacyLevelClosed = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberAccountInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(2, Name = @"role")]
        public uint[] Roles { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"privileges")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong Privileges
        {
            get => __pbn__Privileges ?? 0ul;
            set => __pbn__Privileges = value;
        }
        public bool ShouldSerializePrivileges() => __pbn__Privileges != null;
        public void ResetPrivileges() => __pbn__Privileges = null;
        private ulong? __pbn__Privileges;

        [global::ProtoBuf.ProtoMember(4, Name = @"info")]
        public MemberAccountInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Member : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity", IsRequired = true)]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"state", IsRequired = true)]
        public MemberState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelMembershipState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"description")]
        public global::System.Collections.Generic.List<ChannelDescription> Descriptions { get; } = new global::System.Collections.Generic.List<ChannelDescription>();

        [global::ProtoBuf.ProtoMember(2, Name = @"invitation")]
        public global::System.Collections.Generic.List<ChannelInvitation> Invitations { get; } = new global::System.Collections.Generic.List<ChannelInvitation>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelSlot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reserved")]
        public bool Reserved
        {
            get => __pbn__Reserved.GetValueOrDefault();
            set => __pbn__Reserved = value;
        }
        public bool ShouldSerializeReserved() => __pbn__Reserved != null;
        public void ResetReserved() => __pbn__Reserved = null;
        private bool? __pbn__Reserved;

        [global::ProtoBuf.ProtoMember(2, Name = @"rejoin")]
        public bool Rejoin
        {
            get => __pbn__Rejoin.GetValueOrDefault();
            set => __pbn__Rejoin = value;
        }
        public bool ShouldSerializeRejoin() => __pbn__Rejoin != null;
        public void ResetRejoin() => __pbn__Rejoin = null;
        private bool? __pbn__Rejoin;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public global::bgs.protocol.account.v1.GameAccountHandle Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

        [global::ProtoBuf.ProtoMember(3, Name = @"account_id")]
        public ulong AccountId
        {
            get => __pbn__AccountId.GetValueOrDefault();
            set => __pbn__AccountId = value;
        }
        public bool ShouldSerializeAccountId() => __pbn__AccountId != null;
        public void ResetAccountId() => __pbn__AccountId = null;
        private ulong? __pbn__AccountId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelInvitation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"inviter")]
        public MemberDescription Inviter { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"invitee")]
        public MemberDescription Invitee { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"channel")]
        public ChannelDescription Channel { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slot")]
        public ChannelSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(8, Name = @"expiration_time")]
        public ulong ExpirationTime
        {
            get => __pbn__ExpirationTime.GetValueOrDefault();
            set => __pbn__ExpirationTime = value;
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private ulong? __pbn__ExpirationTime;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
