// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_stream.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamPosition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id", IsPacked = true)]
        public ulong[] StreamIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamAccess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"role", IsPacked = true)]
        public uint[] Roles { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateStreamOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"subject")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Subject
        {
            get => __pbn__Subject ?? "";
            set => __pbn__Subject = value;
        }
        public bool ShouldSerializeSubject() => __pbn__Subject != null;
        public void ResetSubject() => __pbn__Subject = null;
        private string __pbn__Subject;

        [global::ProtoBuf.ProtoMember(4, Name = @"access")]
        public StreamAccess Access { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"voice_level")]
        [global::System.ComponentModel.DefaultValue(StreamVoiceLevel.VoiceLevelDisabled)]
        public StreamVoiceLevel VoiceLevel
        {
            get => __pbn__VoiceLevel ?? StreamVoiceLevel.VoiceLevelDisabled;
            set => __pbn__VoiceLevel = value;
        }
        public bool ShouldSerializeVoiceLevel() => __pbn__VoiceLevel != null;
        public void ResetVoiceLevel() => __pbn__VoiceLevel = null;
        private StreamVoiceLevel? __pbn__VoiceLevel;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Stream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(5, Name = @"subject")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Subject
        {
            get => __pbn__Subject ?? "";
            set => __pbn__Subject = value;
        }
        public bool ShouldSerializeSubject() => __pbn__Subject != null;
        public void ResetSubject() => __pbn__Subject = null;
        private string __pbn__Subject;

        [global::ProtoBuf.ProtoMember(6, Name = @"access")]
        public StreamAccess Access { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"voice_level")]
        [global::System.ComponentModel.DefaultValue(StreamVoiceLevel.VoiceLevelDisabled)]
        public StreamVoiceLevel VoiceLevel
        {
            get => __pbn__VoiceLevel ?? StreamVoiceLevel.VoiceLevelDisabled;
            set => __pbn__VoiceLevel = value;
        }
        public bool ShouldSerializeVoiceLevel() => __pbn__VoiceLevel != null;
        public void ResetVoiceLevel() => __pbn__VoiceLevel = null;
        private StreamVoiceLevel? __pbn__VoiceLevel;

        [global::ProtoBuf.ProtoMember(8, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MentionContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"all")]
        public bool All
        {
            get => __pbn__All.GetValueOrDefault();
            set => __pbn__All = value;
        }
        public bool ShouldSerializeAll() => __pbn__All != null;
        public void ResetAll() => __pbn__All = null;
        private bool? __pbn__All;

        [global::ProtoBuf.ProtoMember(2, Name = @"here")]
        public bool Here
        {
            get => __pbn__Here.GetValueOrDefault();
            set => __pbn__Here = value;
        }
        public bool ShouldSerializeHere() => __pbn__Here != null;
        public void ResetHere() => __pbn__Here = null;
        private bool? __pbn__Here;

        [global::ProtoBuf.ProtoMember(3, Name = @"member_id")]
        public global::System.Collections.Generic.List<MemberId> MemberIds { get; } = new global::System.Collections.Generic.List<MemberId>();

        [global::ProtoBuf.ProtoMember(4, Name = @"role", IsPacked = true)]
        public uint[] Roles { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateMessageOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

        [global::ProtoBuf.ProtoMember(3, Name = @"mention")]
        public MentionContent Mention { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubStreamMessageContainer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public global::System.Collections.Generic.List<StreamMessage> Messages { get; } = new global::System.Collections.Generic.List<StreamMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentChain : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

        [global::ProtoBuf.ProtoMember(6, Name = @"embed")]
        public global::System.Collections.Generic.List<global::bgs.protocol.EmbedInfo> Embeds { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.EmbedInfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"mention")]
        public MentionContent Mention { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"edit_time")]
        public ulong EditTime
        {
            get => __pbn__EditTime.GetValueOrDefault();
            set => __pbn__EditTime = value;
        }
        public bool ShouldSerializeEditTime() => __pbn__EditTime != null;
        public void ResetEditTime() => __pbn__EditTime = null;
        private ulong? __pbn__EditTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public global::bgs.protocol.MessageId Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"author")]
        public MemberDescription Author { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"content_chain")]
        public global::System.Collections.Generic.List<ContentChain> ContentChains { get; } = new global::System.Collections.Generic.List<ContentChain>();

        [global::ProtoBuf.ProtoMember(15, Name = @"destroyer")]
        public MemberDescription Destroyer { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"destroyed")]
        public bool Destroyed
        {
            get => __pbn__Destroyed.GetValueOrDefault();
            set => __pbn__Destroyed = value;
        }
        public bool ShouldSerializeDestroyed() => __pbn__Destroyed != null;
        public void ResetDestroyed() => __pbn__Destroyed = null;
        private bool? __pbn__Destroyed;

        [global::ProtoBuf.ProtoMember(17, Name = @"destroy_time")]
        public ulong DestroyTime
        {
            get => __pbn__DestroyTime.GetValueOrDefault();
            set => __pbn__DestroyTime = value;
        }
        public bool ShouldSerializeDestroyTime() => __pbn__DestroyTime != null;
        public void ResetDestroyTime() => __pbn__DestroyTime = null;
        private ulong? __pbn__DestroyTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamMention : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(2, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(3, Name = @"message_id")]
        public global::bgs.protocol.MessageId MessageId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"author")]
        public MemberDescription Author { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"destroyed")]
        public bool Destroyed
        {
            get => __pbn__Destroyed.GetValueOrDefault();
            set => __pbn__Destroyed = value;
        }
        public bool ShouldSerializeDestroyed() => __pbn__Destroyed != null;
        public void ResetDestroyed() => __pbn__Destroyed = null;
        private bool? __pbn__Destroyed;

        [global::ProtoBuf.ProtoMember(6, Name = @"mention_id")]
        public global::bgs.protocol.TimeSeriesId MentionId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"member_id")]
        public MemberId MemberId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"message")]
        public StreamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(2, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(3, Name = @"marker")]
        public global::bgs.protocol.ViewMarker Marker { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamAdvanceViewTime : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(2, Name = @"view_time")]
        public ulong ViewTime
        {
            get => __pbn__ViewTime.GetValueOrDefault();
            set => __pbn__ViewTime = value;
        }
        public bool ShouldSerializeViewTime() => __pbn__ViewTime != null;
        public void ResetViewTime() => __pbn__ViewTime = null;
        private ulong? __pbn__ViewTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamEventTime : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(2, Name = @"event_time")]
        public ulong EventTime
        {
            get => __pbn__EventTime.GetValueOrDefault();
            set => __pbn__EventTime = value;
        }
        public bool ShouldSerializeEventTime() => __pbn__EventTime != null;
        public void ResetEventTime() => __pbn__EventTime = null;
        private ulong? __pbn__EventTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamMentionView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(2, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(3, Name = @"marker")]
        public global::bgs.protocol.ViewMarker Marker { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamStateOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"subject")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Subject
        {
            get => __pbn__Subject ?? "";
            set => __pbn__Subject = value;
        }
        public bool ShouldSerializeSubject() => __pbn__Subject != null;
        public void ResetSubject() => __pbn__Subject = null;
        private string __pbn__Subject;

        [global::ProtoBuf.ProtoMember(4, Name = @"access")]
        public StreamAccess Access { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"voice_level")]
        [global::System.ComponentModel.DefaultValue(StreamVoiceLevel.VoiceLevelDisabled)]
        public StreamVoiceLevel VoiceLevel
        {
            get => __pbn__VoiceLevel ?? StreamVoiceLevel.VoiceLevelDisabled;
            set => __pbn__VoiceLevel = value;
        }
        public bool ShouldSerializeVoiceLevel() => __pbn__VoiceLevel != null;
        public void ResetVoiceLevel() => __pbn__VoiceLevel = null;
        private StreamVoiceLevel? __pbn__VoiceLevel;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamStateAssignment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(2, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4, Name = @"subject")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Subject
        {
            get => __pbn__Subject ?? "";
            set => __pbn__Subject = value;
        }
        public bool ShouldSerializeSubject() => __pbn__Subject != null;
        public void ResetSubject() => __pbn__Subject = null;
        private string __pbn__Subject;

        [global::ProtoBuf.ProtoMember(5, Name = @"access")]
        public StreamAccess Access { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stream_subscription_removed")]
        public bool StreamSubscriptionRemoved
        {
            get => __pbn__StreamSubscriptionRemoved.GetValueOrDefault();
            set => __pbn__StreamSubscriptionRemoved = value;
        }
        public bool ShouldSerializeStreamSubscriptionRemoved() => __pbn__StreamSubscriptionRemoved != null;
        public void ResetStreamSubscriptionRemoved() => __pbn__StreamSubscriptionRemoved = null;
        private bool? __pbn__StreamSubscriptionRemoved;

        [global::ProtoBuf.ProtoMember(7, Name = @"voice_level")]
        [global::System.ComponentModel.DefaultValue(StreamVoiceLevel.VoiceLevelDisabled)]
        public StreamVoiceLevel VoiceLevel
        {
            get => __pbn__VoiceLevel ?? StreamVoiceLevel.VoiceLevelDisabled;
            set => __pbn__VoiceLevel = value;
        }
        public bool ShouldSerializeVoiceLevel() => __pbn__VoiceLevel != null;
        public void ResetVoiceLevel() => __pbn__VoiceLevel = null;
        private StreamVoiceLevel? __pbn__VoiceLevel;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamTypingIndicator : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"author_id")]
        public MemberId AuthorId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"indicator")]
        [global::System.ComponentModel.DefaultValue(global::bgs.protocol.TypingIndicator.TypingStart)]
        public global::bgs.protocol.TypingIndicator Indicator
        {
            get => __pbn__Indicator ?? global::bgs.protocol.TypingIndicator.TypingStart;
            set => __pbn__Indicator = value;
        }
        public bool ShouldSerializeIndicator() => __pbn__Indicator != null;
        public void ResetIndicator() => __pbn__Indicator = null;
        private global::bgs.protocol.TypingIndicator? __pbn__Indicator;

        [global::ProtoBuf.ProtoMember(3, Name = @"epoch")]
        public ulong Epoch
        {
            get => __pbn__Epoch.GetValueOrDefault();
            set => __pbn__Epoch = value;
        }
        public bool ShouldSerializeEpoch() => __pbn__Epoch != null;
        public void ResetEpoch() => __pbn__Epoch = null;
        private ulong? __pbn__Epoch;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
