// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_request.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public ClubCreateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDescriptionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDescriptionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club")]
        public ClubDescription Club { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetClubTypeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public UniqueClubType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetClubTypeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public UniqueClubType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"role_set")]
        public ClubRoleSet RoleSet { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"range_set")]
        public ClubTypeRangeSet RangeSet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateClubStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public ClubStateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateClubSettingsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public ClubSettingsOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddMemberRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public CreateMemberOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public CreateMemberOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"target_id")]
        public MemberId TargetId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMemberRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"member_id")]
        public MemberId MemberId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMemberResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"member")]
        public Member Member { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMembersRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(4, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMembersResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"member")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateMemberStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"member_id")]
        public MemberId MemberId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"options")]
        public MemberStateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateSubscriberStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public SubscriberStateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AssignRoleRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public RoleOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnassignRoleRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public RoleOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendInvitationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public SendInvitationOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcceptInvitationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InvitationId
        {
            get => __pbn__InvitationId.GetValueOrDefault();
            set => __pbn__InvitationId = value;
        }
        public bool ShouldSerializeInvitationId() => __pbn__InvitationId != null;
        public void ResetInvitationId() => __pbn__InvitationId = null;
        private ulong? __pbn__InvitationId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeclineInvitationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InvitationId
        {
            get => __pbn__InvitationId.GetValueOrDefault();
            set => __pbn__InvitationId = value;
        }
        public bool ShouldSerializeInvitationId() => __pbn__InvitationId != null;
        public void ResetInvitationId() => __pbn__InvitationId = null;
        private ulong? __pbn__InvitationId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RevokeInvitationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InvitationId
        {
            get => __pbn__InvitationId.GetValueOrDefault();
            set => __pbn__InvitationId = value;
        }
        public bool ShouldSerializeInvitationId() => __pbn__InvitationId != null;
        public void ResetInvitationId() => __pbn__InvitationId = null;
        private ulong? __pbn__InvitationId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInvitationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InvitationId
        {
            get => __pbn__InvitationId.GetValueOrDefault();
            set => __pbn__InvitationId = value;
        }
        public bool ShouldSerializeInvitationId() => __pbn__InvitationId != null;
        public void ResetInvitationId() => __pbn__InvitationId = null;
        private ulong? __pbn__InvitationId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInvitationResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"invitation")]
        public ClubInvitation Invitation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInvitationsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInvitationsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"invitation")]
        public global::System.Collections.Generic.List<ClubInvitation> Invitations { get; } = new global::System.Collections.Generic.List<ClubInvitation>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendSuggestionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public SendSuggestionOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcceptSuggestionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"suggestion_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SuggestionId
        {
            get => __pbn__SuggestionId.GetValueOrDefault();
            set => __pbn__SuggestionId = value;
        }
        public bool ShouldSerializeSuggestionId() => __pbn__SuggestionId != null;
        public void ResetSuggestionId() => __pbn__SuggestionId = null;
        private ulong? __pbn__SuggestionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeclineSuggestionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"suggestion_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SuggestionId
        {
            get => __pbn__SuggestionId.GetValueOrDefault();
            set => __pbn__SuggestionId = value;
        }
        public bool ShouldSerializeSuggestionId() => __pbn__SuggestionId != null;
        public void ResetSuggestionId() => __pbn__SuggestionId = null;
        private ulong? __pbn__SuggestionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSuggestionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"suggestion_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SuggestionId
        {
            get => __pbn__SuggestionId.GetValueOrDefault();
            set => __pbn__SuggestionId = value;
        }
        public bool ShouldSerializeSuggestionId() => __pbn__SuggestionId != null;
        public void ResetSuggestionId() => __pbn__SuggestionId = null;
        private ulong? __pbn__SuggestionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSuggestionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"suggestion")]
        public ClubSuggestion Suggestion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSuggestionsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSuggestionsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"suggestion")]
        public global::System.Collections.Generic.List<ClubSuggestion> Suggestions { get; } = new global::System.Collections.Generic.List<ClubSuggestion>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateTicketRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public CreateTicketOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateTicketResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ticket")]
        public ClubTicket Ticket { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroyTicketRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"ticket_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TicketId
        {
            get => __pbn__TicketId ?? "";
            set => __pbn__TicketId = value;
        }
        public bool ShouldSerializeTicketId() => __pbn__TicketId != null;
        public void ResetTicketId() => __pbn__TicketId = null;
        private string __pbn__TicketId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RedeemTicketRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ticket_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TicketId
        {
            get => __pbn__TicketId ?? "";
            set => __pbn__TicketId = value;
        }
        public bool ShouldSerializeTicketId() => __pbn__TicketId != null;
        public void ResetTicketId() => __pbn__TicketId = null;
        private string __pbn__TicketId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTicketRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ticket_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TicketId
        {
            get => __pbn__TicketId ?? "";
            set => __pbn__TicketId = value;
        }
        public bool ShouldSerializeTicketId() => __pbn__TicketId != null;
        public void ResetTicketId() => __pbn__TicketId = null;
        private string __pbn__TicketId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTicketResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ticket")]
        public ClubTicket Ticket { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTicketsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTicketsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ticket")]
        public global::System.Collections.Generic.List<ClubTicket> Tickets { get; } = new global::System.Collections.Generic.List<ClubTicket>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddBanRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public AddBanOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveBanRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"target_id")]
        public MemberId TargetId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBanRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"target_id")]
        public MemberId TargetId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBanResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ban")]
        public ClubBan Ban { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBansRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBansResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ban")]
        public global::System.Collections.Generic.List<ClubBan> Bans { get; } = new global::System.Collections.Generic.List<ClubBan>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong[] StreamIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong[] StreamIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public CreateStreamOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateStreamResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(2, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroyStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream")]
        public Stream Stream { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream")]
        public global::System.Collections.Generic.List<Stream> Streams { get; } = new global::System.Collections.Generic.List<Stream>();

        [global::ProtoBuf.ProtoMember(2, Name = @"view")]
        public global::System.Collections.Generic.List<StreamView> Views { get; } = new global::System.Collections.Generic.List<StreamView>();

        [global::ProtoBuf.ProtoMember(3, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateStreamStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(5, Name = @"options")]
        public StreamStateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetStreamFocusRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"focus")]
        public bool Focus
        {
            get => __pbn__Focus.GetValueOrDefault();
            set => __pbn__Focus = value;
        }
        public bool ShouldSerializeFocus() => __pbn__Focus != null;
        public void ResetFocus() => __pbn__Focus = null;
        private bool? __pbn__Focus;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"options")]
        public CreateMessageOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public StreamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroyMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"message_id")]
        public global::bgs.protocol.MessageId MessageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroyMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public StreamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EditMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"message_id")]
        public global::bgs.protocol.MessageId MessageId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"options")]
        public CreateMessageOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EditMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public StreamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetMessagePinnedRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetTypingIndicatorRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"indicator")]
        [global::System.ComponentModel.DefaultValue(global::bgs.protocol.TypingIndicator.TypingStart)]
        public global::bgs.protocol.TypingIndicator Indicator
        {
            get => __pbn__Indicator ?? global::bgs.protocol.TypingIndicator.TypingStart;
            set => __pbn__Indicator = value;
        }
        public bool ShouldSerializeIndicator() => __pbn__Indicator != null;
        public void ResetIndicator() => __pbn__Indicator = null;
        private global::bgs.protocol.TypingIndicator? __pbn__Indicator;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdvanceStreamViewTimeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id_deprecated")]
        [global::System.Obsolete]
        public ulong StreamIdDeprecated
        {
            get => __pbn__StreamIdDeprecated.GetValueOrDefault();
            set => __pbn__StreamIdDeprecated = value;
        }
        public bool ShouldSerializeStreamIdDeprecated() => __pbn__StreamIdDeprecated != null;
        public void ResetStreamIdDeprecated() => __pbn__StreamIdDeprecated = null;
        private ulong? __pbn__StreamIdDeprecated;

        [global::ProtoBuf.ProtoMember(4, Name = @"stream_id", IsPacked = true)]
        public ulong[] StreamIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdvanceStreamMentionViewTimeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdvanceActivityViewTimeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamHistoryRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"options")]
        public global::bgs.protocol.GetEventOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamHistoryResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public global::System.Collections.Generic.List<StreamMessage> Messages { get; } = new global::System.Collections.Generic.List<StreamMessage>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"message_id")]
        public global::bgs.protocol.MessageId MessageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public StreamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetClubActivityRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public global::bgs.protocol.GetEventOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetClubActivityResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamVoiceTokenRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        public uint Version
        {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamVoiceTokenResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChannelUri
        {
            get => __pbn__ChannelUri ?? "";
            set => __pbn__ChannelUri = value;
        }
        public bool ShouldSerializeChannelUri() => __pbn__ChannelUri != null;
        public void ResetChannelUri() => __pbn__ChannelUri = null;
        private string __pbn__ChannelUri;

        [global::ProtoBuf.ProtoMember(2, Name = @"credentials")]
        public global::bgs.protocol.VoiceCredentials Credentials { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickFromStreamVoiceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public MemberId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_id")]
        public ulong StreamId
        {
            get => __pbn__StreamId.GetValueOrDefault();
            set => __pbn__StreamId = value;
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private ulong? __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(4, Name = @"target_id")]
        public MemberId TargetId { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
