// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_membership_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1.membership
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public global::bgs.protocol.club.v1.ClubMembershipSubscribeOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public global::bgs.protocol.club.v1.ClubMembershipState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public global::bgs.protocol.club.v1.ClubMembershipGetStateOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public global::bgs.protocol.club.v1.ClubMembershipState State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateClubSharedSettingsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public global::bgs.protocol.club.v1.ClubSharedSettingsOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamMentionsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public global::bgs.protocol.GetEventOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"fetch_messages")]
        public bool FetchMessages
        {
            get => __pbn__FetchMessages.GetValueOrDefault();
            set => __pbn__FetchMessages = value;
        }
        public bool ShouldSerializeFetchMessages() => __pbn__FetchMessages != null;
        public void ResetFetchMessages() => __pbn__FetchMessages = null;
        private bool? __pbn__FetchMessages;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamMentionsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mention")]
        public global::System.Collections.Generic.List<global::bgs.protocol.club.v1.StreamMention> Mentions { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.club.v1.StreamMention>();

        [global::ProtoBuf.ProtoMember(2, Name = @"continuation")]
        public ulong Continuation
        {
            get => __pbn__Continuation.GetValueOrDefault();
            set => __pbn__Continuation = value;
        }
        public bool ShouldSerializeContinuation() => __pbn__Continuation != null;
        public void ResetContinuation() => __pbn__Continuation = null;
        private ulong? __pbn__Continuation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveStreamMentionsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"mention_id")]
        public global::System.Collections.Generic.List<global::bgs.protocol.TimeSeriesId> MentionIds { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.TimeSeriesId>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdvanceStreamMentionViewTimeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.AccountId AgentId { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
