// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_range_set.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubTypeRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"name_range")]
        public global::bgs.protocol.UnsignedIntRange NameRange { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"description_range")]
        public global::bgs.protocol.UnsignedIntRange DescriptionRange { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"broadcast_range")]
        public global::bgs.protocol.UnsignedIntRange BroadcastRange { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"short_name_range")]
        public global::bgs.protocol.UnsignedIntRange ShortNameRange { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"member")]
        public ClubMemberRangeSet Member { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"stream")]
        public ClubStreamRangeSet Stream { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"invitation")]
        public ClubInvitationRangeSet Invitation { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"suggestion")]
        public ClubSuggestionRangeSet Suggestion { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"ticket")]
        public ClubTicketRangeSet Ticket { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"ban")]
        public ClubBanRangeSet Ban { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubMemberRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"voice")]
        public global::bgs.protocol.UnsignedIntRange Voice { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"stream_subscriptions")]
        public global::bgs.protocol.UnsignedIntRange StreamSubscriptions { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"note_range")]
        public global::bgs.protocol.UnsignedIntRange NoteRange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubStreamRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name_range")]
        public global::bgs.protocol.UnsignedIntRange NameRange { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"subject_range")]
        public global::bgs.protocol.UnsignedIntRange SubjectRange { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"message_range")]
        public global::bgs.protocol.UnsignedIntRange MessageRange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInvitationRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubSuggestionRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubTicketRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubBanRangeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public global::bgs.protocol.UnsignedIntRange Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"reason_range")]
        public global::bgs.protocol.UnsignedIntRange ReasonRange { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
