// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_role.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubPrivilegeSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"can_destroy")]
        public bool CanDestroy
        {
            get => __pbn__CanDestroy.GetValueOrDefault();
            set => __pbn__CanDestroy = value;
        }
        public bool ShouldSerializeCanDestroy() => __pbn__CanDestroy != null;
        public void ResetCanDestroy() => __pbn__CanDestroy = null;
        private bool? __pbn__CanDestroy;

        [global::ProtoBuf.ProtoMember(10, Name = @"can_set_attribute")]
        public bool CanSetAttribute
        {
            get => __pbn__CanSetAttribute.GetValueOrDefault();
            set => __pbn__CanSetAttribute = value;
        }
        public bool ShouldSerializeCanSetAttribute() => __pbn__CanSetAttribute != null;
        public void ResetCanSetAttribute() => __pbn__CanSetAttribute = null;
        private bool? __pbn__CanSetAttribute;

        [global::ProtoBuf.ProtoMember(11, Name = @"can_set_name")]
        public bool CanSetName
        {
            get => __pbn__CanSetName.GetValueOrDefault();
            set => __pbn__CanSetName = value;
        }
        public bool ShouldSerializeCanSetName() => __pbn__CanSetName != null;
        public void ResetCanSetName() => __pbn__CanSetName = null;
        private bool? __pbn__CanSetName;

        [global::ProtoBuf.ProtoMember(12, Name = @"can_set_description")]
        public bool CanSetDescription
        {
            get => __pbn__CanSetDescription.GetValueOrDefault();
            set => __pbn__CanSetDescription = value;
        }
        public bool ShouldSerializeCanSetDescription() => __pbn__CanSetDescription != null;
        public void ResetCanSetDescription() => __pbn__CanSetDescription = null;
        private bool? __pbn__CanSetDescription;

        [global::ProtoBuf.ProtoMember(13, Name = @"can_set_avatar")]
        public bool CanSetAvatar
        {
            get => __pbn__CanSetAvatar.GetValueOrDefault();
            set => __pbn__CanSetAvatar = value;
        }
        public bool ShouldSerializeCanSetAvatar() => __pbn__CanSetAvatar != null;
        public void ResetCanSetAvatar() => __pbn__CanSetAvatar = null;
        private bool? __pbn__CanSetAvatar;

        [global::ProtoBuf.ProtoMember(14, Name = @"can_set_broadcast")]
        public bool CanSetBroadcast
        {
            get => __pbn__CanSetBroadcast.GetValueOrDefault();
            set => __pbn__CanSetBroadcast = value;
        }
        public bool ShouldSerializeCanSetBroadcast() => __pbn__CanSetBroadcast != null;
        public void ResetCanSetBroadcast() => __pbn__CanSetBroadcast = null;
        private bool? __pbn__CanSetBroadcast;

        [global::ProtoBuf.ProtoMember(15, Name = @"can_set_privacy_level")]
        public bool CanSetPrivacyLevel
        {
            get => __pbn__CanSetPrivacyLevel.GetValueOrDefault();
            set => __pbn__CanSetPrivacyLevel = value;
        }
        public bool ShouldSerializeCanSetPrivacyLevel() => __pbn__CanSetPrivacyLevel != null;
        public void ResetCanSetPrivacyLevel() => __pbn__CanSetPrivacyLevel = null;
        private bool? __pbn__CanSetPrivacyLevel;

        [global::ProtoBuf.ProtoMember(29, Name = @"can_add_member")]
        public bool CanAddMember
        {
            get => __pbn__CanAddMember.GetValueOrDefault();
            set => __pbn__CanAddMember = value;
        }
        public bool ShouldSerializeCanAddMember() => __pbn__CanAddMember != null;
        public void ResetCanAddMember() => __pbn__CanAddMember = null;
        private bool? __pbn__CanAddMember;

        [global::ProtoBuf.ProtoMember(30, Name = @"can_kick_member")]
        public bool CanKickMember
        {
            get => __pbn__CanKickMember.GetValueOrDefault();
            set => __pbn__CanKickMember = value;
        }
        public bool ShouldSerializeCanKickMember() => __pbn__CanKickMember != null;
        public void ResetCanKickMember() => __pbn__CanKickMember = null;
        private bool? __pbn__CanKickMember;

        [global::ProtoBuf.ProtoMember(31, Name = @"can_set_own_member_attribute")]
        public bool CanSetOwnMemberAttribute
        {
            get => __pbn__CanSetOwnMemberAttribute.GetValueOrDefault();
            set => __pbn__CanSetOwnMemberAttribute = value;
        }
        public bool ShouldSerializeCanSetOwnMemberAttribute() => __pbn__CanSetOwnMemberAttribute != null;
        public void ResetCanSetOwnMemberAttribute() => __pbn__CanSetOwnMemberAttribute = null;
        private bool? __pbn__CanSetOwnMemberAttribute;

        [global::ProtoBuf.ProtoMember(32, Name = @"can_set_other_member_attribute")]
        public bool CanSetOtherMemberAttribute
        {
            get => __pbn__CanSetOtherMemberAttribute.GetValueOrDefault();
            set => __pbn__CanSetOtherMemberAttribute = value;
        }
        public bool ShouldSerializeCanSetOtherMemberAttribute() => __pbn__CanSetOtherMemberAttribute != null;
        public void ResetCanSetOtherMemberAttribute() => __pbn__CanSetOtherMemberAttribute = null;
        private bool? __pbn__CanSetOtherMemberAttribute;

        [global::ProtoBuf.ProtoMember(33, Name = @"can_set_own_voice_state")]
        public bool CanSetOwnVoiceState
        {
            get => __pbn__CanSetOwnVoiceState.GetValueOrDefault();
            set => __pbn__CanSetOwnVoiceState = value;
        }
        public bool ShouldSerializeCanSetOwnVoiceState() => __pbn__CanSetOwnVoiceState != null;
        public void ResetCanSetOwnVoiceState() => __pbn__CanSetOwnVoiceState = null;
        private bool? __pbn__CanSetOwnVoiceState;

        [global::ProtoBuf.ProtoMember(34, Name = @"can_set_own_presence_level")]
        public bool CanSetOwnPresenceLevel
        {
            get => __pbn__CanSetOwnPresenceLevel.GetValueOrDefault();
            set => __pbn__CanSetOwnPresenceLevel = value;
        }
        public bool ShouldSerializeCanSetOwnPresenceLevel() => __pbn__CanSetOwnPresenceLevel != null;
        public void ResetCanSetOwnPresenceLevel() => __pbn__CanSetOwnPresenceLevel = null;
        private bool? __pbn__CanSetOwnPresenceLevel;

        [global::ProtoBuf.ProtoMember(35, Name = @"can_set_own_whisper_level")]
        public bool CanSetOwnWhisperLevel
        {
            get => __pbn__CanSetOwnWhisperLevel.GetValueOrDefault();
            set => __pbn__CanSetOwnWhisperLevel = value;
        }
        public bool ShouldSerializeCanSetOwnWhisperLevel() => __pbn__CanSetOwnWhisperLevel != null;
        public void ResetCanSetOwnWhisperLevel() => __pbn__CanSetOwnWhisperLevel = null;
        private bool? __pbn__CanSetOwnWhisperLevel;

        [global::ProtoBuf.ProtoMember(36, Name = @"can_set_own_member_note")]
        public bool CanSetOwnMemberNote
        {
            get => __pbn__CanSetOwnMemberNote.GetValueOrDefault();
            set => __pbn__CanSetOwnMemberNote = value;
        }
        public bool ShouldSerializeCanSetOwnMemberNote() => __pbn__CanSetOwnMemberNote != null;
        public void ResetCanSetOwnMemberNote() => __pbn__CanSetOwnMemberNote = null;
        private bool? __pbn__CanSetOwnMemberNote;

        [global::ProtoBuf.ProtoMember(37, Name = @"can_set_other_member_note")]
        public bool CanSetOtherMemberNote
        {
            get => __pbn__CanSetOtherMemberNote.GetValueOrDefault();
            set => __pbn__CanSetOtherMemberNote = value;
        }
        public bool ShouldSerializeCanSetOtherMemberNote() => __pbn__CanSetOtherMemberNote != null;
        public void ResetCanSetOtherMemberNote() => __pbn__CanSetOtherMemberNote = null;
        private bool? __pbn__CanSetOtherMemberNote;

        [global::ProtoBuf.ProtoMember(50, Name = @"can_use_voice")]
        public bool CanUseVoice
        {
            get => __pbn__CanUseVoice.GetValueOrDefault();
            set => __pbn__CanUseVoice = value;
        }
        public bool ShouldSerializeCanUseVoice() => __pbn__CanUseVoice != null;
        public void ResetCanUseVoice() => __pbn__CanUseVoice = null;
        private bool? __pbn__CanUseVoice;

        [global::ProtoBuf.ProtoMember(51, Name = @"can_voice_mute_member_for_all")]
        public bool CanVoiceMuteMemberForAll
        {
            get => __pbn__CanVoiceMuteMemberForAll.GetValueOrDefault();
            set => __pbn__CanVoiceMuteMemberForAll = value;
        }
        public bool ShouldSerializeCanVoiceMuteMemberForAll() => __pbn__CanVoiceMuteMemberForAll != null;
        public void ResetCanVoiceMuteMemberForAll() => __pbn__CanVoiceMuteMemberForAll = null;
        private bool? __pbn__CanVoiceMuteMemberForAll;

        [global::ProtoBuf.ProtoMember(70, Name = @"can_get_invitation")]
        public bool CanGetInvitation
        {
            get => __pbn__CanGetInvitation.GetValueOrDefault();
            set => __pbn__CanGetInvitation = value;
        }
        public bool ShouldSerializeCanGetInvitation() => __pbn__CanGetInvitation != null;
        public void ResetCanGetInvitation() => __pbn__CanGetInvitation = null;
        private bool? __pbn__CanGetInvitation;

        [global::ProtoBuf.ProtoMember(71, Name = @"can_send_invitation")]
        public bool CanSendInvitation
        {
            get => __pbn__CanSendInvitation.GetValueOrDefault();
            set => __pbn__CanSendInvitation = value;
        }
        public bool ShouldSerializeCanSendInvitation() => __pbn__CanSendInvitation != null;
        public void ResetCanSendInvitation() => __pbn__CanSendInvitation = null;
        private bool? __pbn__CanSendInvitation;

        [global::ProtoBuf.ProtoMember(72, Name = @"can_send_guest_invitation")]
        public bool CanSendGuestInvitation
        {
            get => __pbn__CanSendGuestInvitation.GetValueOrDefault();
            set => __pbn__CanSendGuestInvitation = value;
        }
        public bool ShouldSerializeCanSendGuestInvitation() => __pbn__CanSendGuestInvitation != null;
        public void ResetCanSendGuestInvitation() => __pbn__CanSendGuestInvitation = null;
        private bool? __pbn__CanSendGuestInvitation;

        [global::ProtoBuf.ProtoMember(73, Name = @"can_revoke_own_invitation")]
        public bool CanRevokeOwnInvitation
        {
            get => __pbn__CanRevokeOwnInvitation.GetValueOrDefault();
            set => __pbn__CanRevokeOwnInvitation = value;
        }
        public bool ShouldSerializeCanRevokeOwnInvitation() => __pbn__CanRevokeOwnInvitation != null;
        public void ResetCanRevokeOwnInvitation() => __pbn__CanRevokeOwnInvitation = null;
        private bool? __pbn__CanRevokeOwnInvitation;

        [global::ProtoBuf.ProtoMember(74, Name = @"can_revoke_other_invitation")]
        public bool CanRevokeOtherInvitation
        {
            get => __pbn__CanRevokeOtherInvitation.GetValueOrDefault();
            set => __pbn__CanRevokeOtherInvitation = value;
        }
        public bool ShouldSerializeCanRevokeOtherInvitation() => __pbn__CanRevokeOtherInvitation != null;
        public void ResetCanRevokeOtherInvitation() => __pbn__CanRevokeOtherInvitation = null;
        private bool? __pbn__CanRevokeOtherInvitation;

        [global::ProtoBuf.ProtoMember(90, Name = @"can_get_suggestion")]
        public bool CanGetSuggestion
        {
            get => __pbn__CanGetSuggestion.GetValueOrDefault();
            set => __pbn__CanGetSuggestion = value;
        }
        public bool ShouldSerializeCanGetSuggestion() => __pbn__CanGetSuggestion != null;
        public void ResetCanGetSuggestion() => __pbn__CanGetSuggestion = null;
        private bool? __pbn__CanGetSuggestion;

        [global::ProtoBuf.ProtoMember(91, Name = @"can_suggest_member")]
        public bool CanSuggestMember
        {
            get => __pbn__CanSuggestMember.GetValueOrDefault();
            set => __pbn__CanSuggestMember = value;
        }
        public bool ShouldSerializeCanSuggestMember() => __pbn__CanSuggestMember != null;
        public void ResetCanSuggestMember() => __pbn__CanSuggestMember = null;
        private bool? __pbn__CanSuggestMember;

        [global::ProtoBuf.ProtoMember(92, Name = @"can_approve_member")]
        public bool CanApproveMember
        {
            get => __pbn__CanApproveMember.GetValueOrDefault();
            set => __pbn__CanApproveMember = value;
        }
        public bool ShouldSerializeCanApproveMember() => __pbn__CanApproveMember != null;
        public void ResetCanApproveMember() => __pbn__CanApproveMember = null;
        private bool? __pbn__CanApproveMember;

        [global::ProtoBuf.ProtoMember(110, Name = @"can_get_ticket")]
        public bool CanGetTicket
        {
            get => __pbn__CanGetTicket.GetValueOrDefault();
            set => __pbn__CanGetTicket = value;
        }
        public bool ShouldSerializeCanGetTicket() => __pbn__CanGetTicket != null;
        public void ResetCanGetTicket() => __pbn__CanGetTicket = null;
        private bool? __pbn__CanGetTicket;

        [global::ProtoBuf.ProtoMember(111, Name = @"can_create_ticket")]
        public bool CanCreateTicket
        {
            get => __pbn__CanCreateTicket.GetValueOrDefault();
            set => __pbn__CanCreateTicket = value;
        }
        public bool ShouldSerializeCanCreateTicket() => __pbn__CanCreateTicket != null;
        public void ResetCanCreateTicket() => __pbn__CanCreateTicket = null;
        private bool? __pbn__CanCreateTicket;

        [global::ProtoBuf.ProtoMember(112, Name = @"can_destroy_ticket")]
        public bool CanDestroyTicket
        {
            get => __pbn__CanDestroyTicket.GetValueOrDefault();
            set => __pbn__CanDestroyTicket = value;
        }
        public bool ShouldSerializeCanDestroyTicket() => __pbn__CanDestroyTicket != null;
        public void ResetCanDestroyTicket() => __pbn__CanDestroyTicket = null;
        private bool? __pbn__CanDestroyTicket;

        [global::ProtoBuf.ProtoMember(130, Name = @"can_get_ban")]
        public bool CanGetBan
        {
            get => __pbn__CanGetBan.GetValueOrDefault();
            set => __pbn__CanGetBan = value;
        }
        public bool ShouldSerializeCanGetBan() => __pbn__CanGetBan != null;
        public void ResetCanGetBan() => __pbn__CanGetBan = null;
        private bool? __pbn__CanGetBan;

        [global::ProtoBuf.ProtoMember(131, Name = @"can_add_ban")]
        public bool CanAddBan
        {
            get => __pbn__CanAddBan.GetValueOrDefault();
            set => __pbn__CanAddBan = value;
        }
        public bool ShouldSerializeCanAddBan() => __pbn__CanAddBan != null;
        public void ResetCanAddBan() => __pbn__CanAddBan = null;
        private bool? __pbn__CanAddBan;

        [global::ProtoBuf.ProtoMember(132, Name = @"can_remove_ban")]
        public bool CanRemoveBan
        {
            get => __pbn__CanRemoveBan.GetValueOrDefault();
            set => __pbn__CanRemoveBan = value;
        }
        public bool ShouldSerializeCanRemoveBan() => __pbn__CanRemoveBan != null;
        public void ResetCanRemoveBan() => __pbn__CanRemoveBan = null;
        private bool? __pbn__CanRemoveBan;

        [global::ProtoBuf.ProtoMember(140, Name = @"can_create_stream")]
        public bool CanCreateStream
        {
            get => __pbn__CanCreateStream.GetValueOrDefault();
            set => __pbn__CanCreateStream = value;
        }
        public bool ShouldSerializeCanCreateStream() => __pbn__CanCreateStream != null;
        public void ResetCanCreateStream() => __pbn__CanCreateStream = null;
        private bool? __pbn__CanCreateStream;

        [global::ProtoBuf.ProtoMember(141, Name = @"can_destroy_stream")]
        public bool CanDestroyStream
        {
            get => __pbn__CanDestroyStream.GetValueOrDefault();
            set => __pbn__CanDestroyStream = value;
        }
        public bool ShouldSerializeCanDestroyStream() => __pbn__CanDestroyStream != null;
        public void ResetCanDestroyStream() => __pbn__CanDestroyStream = null;
        private bool? __pbn__CanDestroyStream;

        [global::ProtoBuf.ProtoMember(142, Name = @"can_set_stream_position")]
        public bool CanSetStreamPosition
        {
            get => __pbn__CanSetStreamPosition.GetValueOrDefault();
            set => __pbn__CanSetStreamPosition = value;
        }
        public bool ShouldSerializeCanSetStreamPosition() => __pbn__CanSetStreamPosition != null;
        public void ResetCanSetStreamPosition() => __pbn__CanSetStreamPosition = null;
        private bool? __pbn__CanSetStreamPosition;

        [global::ProtoBuf.ProtoMember(143, Name = @"can_set_stream_attribute")]
        public bool CanSetStreamAttribute
        {
            get => __pbn__CanSetStreamAttribute.GetValueOrDefault();
            set => __pbn__CanSetStreamAttribute = value;
        }
        public bool ShouldSerializeCanSetStreamAttribute() => __pbn__CanSetStreamAttribute != null;
        public void ResetCanSetStreamAttribute() => __pbn__CanSetStreamAttribute = null;
        private bool? __pbn__CanSetStreamAttribute;

        [global::ProtoBuf.ProtoMember(144, Name = @"can_set_stream_name")]
        public bool CanSetStreamName
        {
            get => __pbn__CanSetStreamName.GetValueOrDefault();
            set => __pbn__CanSetStreamName = value;
        }
        public bool ShouldSerializeCanSetStreamName() => __pbn__CanSetStreamName != null;
        public void ResetCanSetStreamName() => __pbn__CanSetStreamName = null;
        private bool? __pbn__CanSetStreamName;

        [global::ProtoBuf.ProtoMember(145, Name = @"can_set_stream_subject")]
        public bool CanSetStreamSubject
        {
            get => __pbn__CanSetStreamSubject.GetValueOrDefault();
            set => __pbn__CanSetStreamSubject = value;
        }
        public bool ShouldSerializeCanSetStreamSubject() => __pbn__CanSetStreamSubject != null;
        public void ResetCanSetStreamSubject() => __pbn__CanSetStreamSubject = null;
        private bool? __pbn__CanSetStreamSubject;

        [global::ProtoBuf.ProtoMember(146, Name = @"can_set_stream_access")]
        public bool CanSetStreamAccess
        {
            get => __pbn__CanSetStreamAccess.GetValueOrDefault();
            set => __pbn__CanSetStreamAccess = value;
        }
        public bool ShouldSerializeCanSetStreamAccess() => __pbn__CanSetStreamAccess != null;
        public void ResetCanSetStreamAccess() => __pbn__CanSetStreamAccess = null;
        private bool? __pbn__CanSetStreamAccess;

        [global::ProtoBuf.ProtoMember(147, Name = @"can_set_stream_voice_level")]
        public bool CanSetStreamVoiceLevel
        {
            get => __pbn__CanSetStreamVoiceLevel.GetValueOrDefault();
            set => __pbn__CanSetStreamVoiceLevel = value;
        }
        public bool ShouldSerializeCanSetStreamVoiceLevel() => __pbn__CanSetStreamVoiceLevel != null;
        public void ResetCanSetStreamVoiceLevel() => __pbn__CanSetStreamVoiceLevel = null;
        private bool? __pbn__CanSetStreamVoiceLevel;

        [global::ProtoBuf.ProtoMember(180, Name = @"can_create_message")]
        public bool CanCreateMessage
        {
            get => __pbn__CanCreateMessage.GetValueOrDefault();
            set => __pbn__CanCreateMessage = value;
        }
        public bool ShouldSerializeCanCreateMessage() => __pbn__CanCreateMessage != null;
        public void ResetCanCreateMessage() => __pbn__CanCreateMessage = null;
        private bool? __pbn__CanCreateMessage;

        [global::ProtoBuf.ProtoMember(181, Name = @"can_destroy_own_message")]
        public bool CanDestroyOwnMessage
        {
            get => __pbn__CanDestroyOwnMessage.GetValueOrDefault();
            set => __pbn__CanDestroyOwnMessage = value;
        }
        public bool ShouldSerializeCanDestroyOwnMessage() => __pbn__CanDestroyOwnMessage != null;
        public void ResetCanDestroyOwnMessage() => __pbn__CanDestroyOwnMessage = null;
        private bool? __pbn__CanDestroyOwnMessage;

        [global::ProtoBuf.ProtoMember(182, Name = @"can_destroy_other_message")]
        public bool CanDestroyOtherMessage
        {
            get => __pbn__CanDestroyOtherMessage.GetValueOrDefault();
            set => __pbn__CanDestroyOtherMessage = value;
        }
        public bool ShouldSerializeCanDestroyOtherMessage() => __pbn__CanDestroyOtherMessage != null;
        public void ResetCanDestroyOtherMessage() => __pbn__CanDestroyOtherMessage = null;
        private bool? __pbn__CanDestroyOtherMessage;

        [global::ProtoBuf.ProtoMember(183, Name = @"can_edit_own_message")]
        public bool CanEditOwnMessage
        {
            get => __pbn__CanEditOwnMessage.GetValueOrDefault();
            set => __pbn__CanEditOwnMessage = value;
        }
        public bool ShouldSerializeCanEditOwnMessage() => __pbn__CanEditOwnMessage != null;
        public void ResetCanEditOwnMessage() => __pbn__CanEditOwnMessage = null;
        private bool? __pbn__CanEditOwnMessage;

        [global::ProtoBuf.ProtoMember(184, Name = @"can_pin_message")]
        public bool CanPinMessage
        {
            get => __pbn__CanPinMessage.GetValueOrDefault();
            set => __pbn__CanPinMessage = value;
        }
        public bool ShouldSerializeCanPinMessage() => __pbn__CanPinMessage != null;
        public void ResetCanPinMessage() => __pbn__CanPinMessage = null;
        private bool? __pbn__CanPinMessage;

        [global::ProtoBuf.ProtoMember(185, Name = @"can_mention_all")]
        public bool CanMentionAll
        {
            get => __pbn__CanMentionAll.GetValueOrDefault();
            set => __pbn__CanMentionAll = value;
        }
        public bool ShouldSerializeCanMentionAll() => __pbn__CanMentionAll != null;
        public void ResetCanMentionAll() => __pbn__CanMentionAll = null;
        private bool? __pbn__CanMentionAll;

        [global::ProtoBuf.ProtoMember(186, Name = @"can_mention_here")]
        public bool CanMentionHere
        {
            get => __pbn__CanMentionHere.GetValueOrDefault();
            set => __pbn__CanMentionHere = value;
        }
        public bool ShouldSerializeCanMentionHere() => __pbn__CanMentionHere != null;
        public void ResetCanMentionHere() => __pbn__CanMentionHere = null;
        private bool? __pbn__CanMentionHere;

        [global::ProtoBuf.ProtoMember(187, Name = @"can_mention_member")]
        public bool CanMentionMember
        {
            get => __pbn__CanMentionMember.GetValueOrDefault();
            set => __pbn__CanMentionMember = value;
        }
        public bool ShouldSerializeCanMentionMember() => __pbn__CanMentionMember != null;
        public void ResetCanMentionMember() => __pbn__CanMentionMember = null;
        private bool? __pbn__CanMentionMember;

        [global::ProtoBuf.ProtoMember(188, Name = @"can_mention_role")]
        public bool CanMentionRole
        {
            get => __pbn__CanMentionRole.GetValueOrDefault();
            set => __pbn__CanMentionRole = value;
        }
        public bool ShouldSerializeCanMentionRole() => __pbn__CanMentionRole != null;
        public void ResetCanMentionRole() => __pbn__CanMentionRole = null;
        private bool? __pbn__CanMentionRole;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"state")]
        public global::bgs.protocol.RoleState State { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"privilege")]
        public ClubPrivilegeSet Privilege { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"always_grant_stream_access")]
        public bool AlwaysGrantStreamAccess
        {
            get => __pbn__AlwaysGrantStreamAccess.GetValueOrDefault();
            set => __pbn__AlwaysGrantStreamAccess = value;
        }
        public bool ShouldSerializeAlwaysGrantStreamAccess() => __pbn__AlwaysGrantStreamAccess != null;
        public void ResetAlwaysGrantStreamAccess() => __pbn__AlwaysGrantStreamAccess = null;
        private bool? __pbn__AlwaysGrantStreamAccess;

        [global::ProtoBuf.ProtoMember(5, Name = @"allow_in_club_slot")]
        public bool AllowInClubSlot
        {
            get => __pbn__AllowInClubSlot.GetValueOrDefault();
            set => __pbn__AllowInClubSlot = value;
        }
        public bool ShouldSerializeAllowInClubSlot() => __pbn__AllowInClubSlot != null;
        public void ResetAllowInClubSlot() => __pbn__AllowInClubSlot = null;
        private bool? __pbn__AllowInClubSlot;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubRoleSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"role")]
        public global::System.Collections.Generic.List<ClubRole> Roles { get; } = new global::System.Collections.Generic.List<ClubRole>();

        [global::ProtoBuf.ProtoMember(5, Name = @"default_role", IsPacked = true)]
        public uint[] DefaultRoles { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"assignment_respects_relegation_chain")]
        public bool AssignmentRespectsRelegationChain
        {
            get => __pbn__AssignmentRespectsRelegationChain.GetValueOrDefault();
            set => __pbn__AssignmentRespectsRelegationChain = value;
        }
        public bool ShouldSerializeAssignmentRespectsRelegationChain() => __pbn__AssignmentRespectsRelegationChain != null;
        public void ResetAssignmentRespectsRelegationChain() => __pbn__AssignmentRespectsRelegationChain = null;
        private bool? __pbn__AssignmentRespectsRelegationChain;

        [global::ProtoBuf.ProtoMember(7, Name = @"subtype")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Subtype
        {
            get => __pbn__Subtype ?? "";
            set => __pbn__Subtype = value;
        }
        public bool ShouldSerializeSubtype() => __pbn__Subtype != null;
        public void ResetSubtype() => __pbn__Subtype = null;
        private string __pbn__Subtype;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
