// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: club_invitation.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.club.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubSlot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"role")]
        public uint Role
        {
            get => __pbn__Role.GetValueOrDefault();
            set => __pbn__Role = value;
        }
        public bool ShouldSerializeRole() => __pbn__Role != null;
        public void ResetRole() => __pbn__Role = null;
        private uint? __pbn__Role;

        [global::ProtoBuf.ProtoMember(2, Name = @"default_stream_id")]
        public ulong DefaultStreamId
        {
            get => __pbn__DefaultStreamId.GetValueOrDefault();
            set => __pbn__DefaultStreamId = value;
        }
        public bool ShouldSerializeDefaultStreamId() => __pbn__DefaultStreamId != null;
        public void ResetDefaultStreamId() => __pbn__DefaultStreamId = null;
        private ulong? __pbn__DefaultStreamId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendInvitationOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_id")]
        public MemberId TargetId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInvitation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"inviter")]
        public MemberDescription Inviter { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"invitee")]
        public MemberDescription Invitee { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"club")]
        public ClubDescription Club { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(7, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(8, Name = @"expiration_time")]
        public ulong ExpirationTime
        {
            get => __pbn__ExpirationTime.GetValueOrDefault();
            set => __pbn__ExpirationTime = value;
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private ulong? __pbn__ExpirationTime;

        [global::ProtoBuf.ProtoMember(9, Name = @"suggester")]
        public MemberDescription Suggester { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendSuggestionOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_id")]
        public MemberId TargetId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubSuggestion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

        [global::ProtoBuf.ProtoMember(3, Name = @"suggester")]
        public MemberDescription Suggester { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"suggestee")]
        public MemberDescription Suggestee { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(7, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(8, Name = @"expiration_time")]
        public ulong ExpirationTime
        {
            get => __pbn__ExpirationTime.GetValueOrDefault();
            set => __pbn__ExpirationTime = value;
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private ulong? __pbn__ExpirationTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateTicketOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(3, Name = @"allowed_redeem_count")]
        public uint AllowedRedeemCount
        {
            get => __pbn__AllowedRedeemCount.GetValueOrDefault();
            set => __pbn__AllowedRedeemCount = value;
        }
        public bool ShouldSerializeAllowedRedeemCount() => __pbn__AllowedRedeemCount != null;
        public void ResetAllowedRedeemCount() => __pbn__AllowedRedeemCount = null;
        private uint? __pbn__AllowedRedeemCount;

        [global::ProtoBuf.ProtoMember(4, Name = @"expiration_time")]
        public ulong ExpirationTime
        {
            get => __pbn__ExpirationTime.GetValueOrDefault();
            set => __pbn__ExpirationTime = value;
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private ulong? __pbn__ExpirationTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubTicket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id
        {
            get => __pbn__Id ?? "";
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private string __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"creator")]
        public MemberDescription Creator { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"club")]
        public ClubDescription Club { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"slot")]
        public ClubSlot Slot { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(6, Name = @"current_redeem_count")]
        public uint CurrentRedeemCount
        {
            get => __pbn__CurrentRedeemCount.GetValueOrDefault();
            set => __pbn__CurrentRedeemCount = value;
        }
        public bool ShouldSerializeCurrentRedeemCount() => __pbn__CurrentRedeemCount != null;
        public void ResetCurrentRedeemCount() => __pbn__CurrentRedeemCount = null;
        private uint? __pbn__CurrentRedeemCount;

        [global::ProtoBuf.ProtoMember(7, Name = @"allowed_redeem_count")]
        public uint AllowedRedeemCount
        {
            get => __pbn__AllowedRedeemCount.GetValueOrDefault();
            set => __pbn__AllowedRedeemCount = value;
        }
        public bool ShouldSerializeAllowedRedeemCount() => __pbn__AllowedRedeemCount != null;
        public void ResetAllowedRedeemCount() => __pbn__AllowedRedeemCount = null;
        private uint? __pbn__AllowedRedeemCount;

        [global::ProtoBuf.ProtoMember(8, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(9, Name = @"expiration_time")]
        public ulong ExpirationTime
        {
            get => __pbn__ExpirationTime.GetValueOrDefault();
            set => __pbn__ExpirationTime = value;
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private ulong? __pbn__ExpirationTime;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
