// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: presence_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.presence.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.EntityId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_id", IsRequired = true)]
        public ulong ObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint[] Programs { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"flag_public")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool FlagPublic
        {
            get => __pbn__FlagPublic ?? true;
            set => __pbn__FlagPublic = value;
        }
        public bool ShouldSerializeFlagPublic() => __pbn__FlagPublic != null;
        public void ResetFlagPublic() => __pbn__FlagPublic = null;
        private bool? __pbn__FlagPublic;

        [global::ProtoBuf.ProtoMember(6, Name = @"key")]
        public global::System.Collections.Generic.List<FieldKey> Keys { get; } = new global::System.Collections.Generic.List<FieldKey>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeNotificationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.EntityId AgentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_id")]
        public ulong ObjectId
        {
            get => __pbn__ObjectId.GetValueOrDefault();
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"field_operation")]
        public global::System.Collections.Generic.List<FieldOperation> FieldOperations { get; } = new global::System.Collections.Generic.List<FieldOperation>();

        [global::ProtoBuf.ProtoMember(3, Name = @"no_create")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool NoCreate
        {
            get => __pbn__NoCreate ?? false;
            set => __pbn__NoCreate = value;
        }
        public bool ShouldSerializeNoCreate() => __pbn__NoCreate != null;
        public void ResetNoCreate() => __pbn__NoCreate = null;
        private bool? __pbn__NoCreate;

        [global::ProtoBuf.ProtoMember(4, Name = @"agent_id")]
        public global::bgs.protocol.EntityId AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public global::System.Collections.Generic.List<FieldKey> Keys { get; } = new global::System.Collections.Generic.List<FieldKey>();

        [global::ProtoBuf.ProtoMember(3, Name = @"agent_id")]
        public global::bgs.protocol.EntityId AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"field")]
        public global::System.Collections.Generic.List<Field> Fields { get; } = new global::System.Collections.Generic.List<Field>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OwnershipRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"release_ownership")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ReleaseOwnership
        {
            get => __pbn__ReleaseOwnership ?? false;
            set => __pbn__ReleaseOwnership = value;
        }
        public bool ShouldSerializeReleaseOwnership() => __pbn__ReleaseOwnership != null;
        public void ResetReleaseOwnership() => __pbn__ReleaseOwnership = null;
        private bool? __pbn__ReleaseOwnership;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
