// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: report_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.report.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(10, Name = @"custom_report")]
        public CustomReport CustomReport { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"spam_report")]
        public SpamReport SpamReport { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"harassment_report")]
        public HarassmentReport HarassmentReport { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"real_life_threat_report")]
        public RealLifeThreatReport RealLifeThreatReport { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"inappropriate_battle_tag_report")]
        public InappropriateBattleTagReport InappropriateBattleTagReport { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"hacking_report")]
        public HackingReport HackingReport { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"botting_report")]
        public BottingReport BottingReport { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type
        {
            get => __pbn__Type ?? "";
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private string __pbn__Type;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string programId
        {
            get => __pbn__programId ?? "";
            set => __pbn__programId = value;
        }
        public bool ShouldSerializeprogramId() => __pbn__programId != null;
        public void ResetprogramId() => __pbn__programId = null;
        private string __pbn__programId;

        [global::ProtoBuf.ProtoMember(3, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpamReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"source")]
        [global::System.ComponentModel.DefaultValue(SpamSource.Other)]
        public SpamSource Source
        {
            get => __pbn__Source ?? SpamSource.Other;
            set => __pbn__Source = value;
        }
        public bool ShouldSerializeSource() => __pbn__Source != null;
        public void ResetSource() => __pbn__Source = null;
        private SpamSource? __pbn__Source;

        [global::ProtoBuf.ProtoContract()]
        public enum SpamSource
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OTHER")]
            Other = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FRIEND_INVITE")]
            FriendInvite = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"WHISPER")]
            Whisper = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CHAT")]
            Chat = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HarassmentReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get => __pbn__Text ?? "";
            set => __pbn__Text = value;
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RealLifeThreatReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get => __pbn__Text ?? "";
            set => __pbn__Text = value;
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InappropriateBattleTagReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HackingReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BottingReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public global::bgs.protocol.account.v1.GameAccountHandle Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Report : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"report_type", IsRequired = true)]
        public string ReportType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attribute")]
        public global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.v2.Attribute>();

        [global::ProtoBuf.ProtoMember(3, Name = @"report_qos")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int ReportQos
        {
            get => __pbn__ReportQos ?? 0;
            set => __pbn__ReportQos = value;
        }
        public bool ShouldSerializeReportQos() => __pbn__ReportQos != null;
        public void ResetReportQos() => __pbn__ReportQos = null;
        private int? __pbn__ReportQos;

        [global::ProtoBuf.ProtoMember(4, Name = @"reporting_account")]
        public global::bgs.protocol.EntityId ReportingAccount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"reporting_game_account")]
        public global::bgs.protocol.EntityId ReportingGameAccount { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"report_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ReportTimestamp
        {
            get => __pbn__ReportTimestamp.GetValueOrDefault();
            set => __pbn__ReportTimestamp = value;
        }
        public bool ShouldSerializeReportTimestamp() => __pbn__ReportTimestamp != null;
        public void ResetReportTimestamp() => __pbn__ReportTimestamp = null;
        private ulong? __pbn__ReportTimestamp;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
