// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: rpc_config.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.config
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RPCMethodConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"service_name")]
        [global::System.ComponentModel.DefaultValue("")]
        [global::System.Obsolete]
        public string ServiceName
        {
            get => __pbn__ServiceName ?? "";
            set => __pbn__ServiceName = value;
        }
        public bool ShouldSerializeServiceName() => __pbn__ServiceName != null;
        public void ResetServiceName() => __pbn__ServiceName = null;
        private string __pbn__ServiceName;

        [global::ProtoBuf.ProtoMember(2, Name = @"method_name")]
        [global::System.ComponentModel.DefaultValue("")]
        [global::System.Obsolete]
        public string MethodName
        {
            get => __pbn__MethodName ?? "";
            set => __pbn__MethodName = value;
        }
        public bool ShouldSerializeMethodName() => __pbn__MethodName != null;
        public void ResetMethodName() => __pbn__MethodName = null;
        private string __pbn__MethodName;

        [global::ProtoBuf.ProtoMember(3, Name = @"fixed_call_cost")]
        [global::System.ComponentModel.DefaultValue(1u)]
        public uint FixedCallCost
        {
            get => __pbn__FixedCallCost ?? 1u;
            set => __pbn__FixedCallCost = value;
        }
        public bool ShouldSerializeFixedCallCost() => __pbn__FixedCallCost != null;
        public void ResetFixedCallCost() => __pbn__FixedCallCost = null;
        private uint? __pbn__FixedCallCost;

        [global::ProtoBuf.ProtoMember(4, Name = @"fixed_packet_size")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint FixedPacketSize
        {
            get => __pbn__FixedPacketSize ?? 0u;
            set => __pbn__FixedPacketSize = value;
        }
        public bool ShouldSerializeFixedPacketSize() => __pbn__FixedPacketSize != null;
        public void ResetFixedPacketSize() => __pbn__FixedPacketSize = null;
        private uint? __pbn__FixedPacketSize;

        [global::ProtoBuf.ProtoMember(5, Name = @"variable_multiplier")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float VariableMultiplier
        {
            get => __pbn__VariableMultiplier ?? 0f;
            set => __pbn__VariableMultiplier = value;
        }
        public bool ShouldSerializeVariableMultiplier() => __pbn__VariableMultiplier != null;
        public void ResetVariableMultiplier() => __pbn__VariableMultiplier = null;
        private float? __pbn__VariableMultiplier;

        [global::ProtoBuf.ProtoMember(6, Name = @"multiplier")]
        [global::System.ComponentModel.DefaultValue(1f)]
        public float Multiplier
        {
            get => __pbn__Multiplier ?? 1f;
            set => __pbn__Multiplier = value;
        }
        public bool ShouldSerializeMultiplier() => __pbn__Multiplier != null;
        public void ResetMultiplier() => __pbn__Multiplier = null;
        private float? __pbn__Multiplier;

        [global::ProtoBuf.ProtoMember(7, Name = @"rate_limit_count")]
        public uint RateLimitCount
        {
            get => __pbn__RateLimitCount.GetValueOrDefault();
            set => __pbn__RateLimitCount = value;
        }
        public bool ShouldSerializeRateLimitCount() => __pbn__RateLimitCount != null;
        public void ResetRateLimitCount() => __pbn__RateLimitCount = null;
        private uint? __pbn__RateLimitCount;

        [global::ProtoBuf.ProtoMember(8, Name = @"rate_limit_seconds")]
        public uint RateLimitSeconds
        {
            get => __pbn__RateLimitSeconds.GetValueOrDefault();
            set => __pbn__RateLimitSeconds = value;
        }
        public bool ShouldSerializeRateLimitSeconds() => __pbn__RateLimitSeconds != null;
        public void ResetRateLimitSeconds() => __pbn__RateLimitSeconds = null;
        private uint? __pbn__RateLimitSeconds;

        [global::ProtoBuf.ProtoMember(9, Name = @"max_packet_size")]
        public uint MaxPacketSize
        {
            get => __pbn__MaxPacketSize.GetValueOrDefault();
            set => __pbn__MaxPacketSize = value;
        }
        public bool ShouldSerializeMaxPacketSize() => __pbn__MaxPacketSize != null;
        public void ResetMaxPacketSize() => __pbn__MaxPacketSize = null;
        private uint? __pbn__MaxPacketSize;

        [global::ProtoBuf.ProtoMember(10, Name = @"max_encoded_size")]
        public uint MaxEncodedSize
        {
            get => __pbn__MaxEncodedSize.GetValueOrDefault();
            set => __pbn__MaxEncodedSize = value;
        }
        public bool ShouldSerializeMaxEncodedSize() => __pbn__MaxEncodedSize != null;
        public void ResetMaxEncodedSize() => __pbn__MaxEncodedSize = null;
        private uint? __pbn__MaxEncodedSize;

        [global::ProtoBuf.ProtoMember(11, Name = @"timeout")]
        public float Timeout
        {
            get => __pbn__Timeout.GetValueOrDefault();
            set => __pbn__Timeout = value;
        }
        public bool ShouldSerializeTimeout() => __pbn__Timeout != null;
        public void ResetTimeout() => __pbn__Timeout = null;
        private float? __pbn__Timeout;

        [global::ProtoBuf.ProtoMember(12, Name = @"cap_balance")]
        public uint CapBalance
        {
            get => __pbn__CapBalance.GetValueOrDefault();
            set => __pbn__CapBalance = value;
        }
        public bool ShouldSerializeCapBalance() => __pbn__CapBalance != null;
        public void ResetCapBalance() => __pbn__CapBalance = null;
        private uint? __pbn__CapBalance;

        [global::ProtoBuf.ProtoMember(13, Name = @"income_per_second")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float IncomePerSecond
        {
            get => __pbn__IncomePerSecond ?? 0f;
            set => __pbn__IncomePerSecond = value;
        }
        public bool ShouldSerializeIncomePerSecond() => __pbn__IncomePerSecond != null;
        public void ResetIncomePerSecond() => __pbn__IncomePerSecond = null;
        private float? __pbn__IncomePerSecond;

        [global::ProtoBuf.ProtoMember(14, Name = @"service_hash")]
        public uint ServiceHash
        {
            get => __pbn__ServiceHash.GetValueOrDefault();
            set => __pbn__ServiceHash = value;
        }
        public bool ShouldSerializeServiceHash() => __pbn__ServiceHash != null;
        public void ResetServiceHash() => __pbn__ServiceHash = null;
        private uint? __pbn__ServiceHash;

        [global::ProtoBuf.ProtoMember(15, Name = @"method_id")]
        public uint MethodId
        {
            get => __pbn__MethodId.GetValueOrDefault();
            set => __pbn__MethodId = value;
        }
        public bool ShouldSerializeMethodId() => __pbn__MethodId != null;
        public void ResetMethodId() => __pbn__MethodId = null;
        private uint? __pbn__MethodId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RPCMeterConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"method")]
        public global::System.Collections.Generic.List<RPCMethodConfig> Methods { get; } = new global::System.Collections.Generic.List<RPCMethodConfig>();

        [global::ProtoBuf.ProtoMember(2, Name = @"income_per_second")]
        [global::System.ComponentModel.DefaultValue(1u)]
        public uint IncomePerSecond
        {
            get => __pbn__IncomePerSecond ?? 1u;
            set => __pbn__IncomePerSecond = value;
        }
        public bool ShouldSerializeIncomePerSecond() => __pbn__IncomePerSecond != null;
        public void ResetIncomePerSecond() => __pbn__IncomePerSecond = null;
        private uint? __pbn__IncomePerSecond;

        [global::ProtoBuf.ProtoMember(3, Name = @"initial_balance")]
        public uint InitialBalance
        {
            get => __pbn__InitialBalance.GetValueOrDefault();
            set => __pbn__InitialBalance = value;
        }
        public bool ShouldSerializeInitialBalance() => __pbn__InitialBalance != null;
        public void ResetInitialBalance() => __pbn__InitialBalance = null;
        private uint? __pbn__InitialBalance;

        [global::ProtoBuf.ProtoMember(4, Name = @"cap_balance")]
        public uint CapBalance
        {
            get => __pbn__CapBalance.GetValueOrDefault();
            set => __pbn__CapBalance = value;
        }
        public bool ShouldSerializeCapBalance() => __pbn__CapBalance != null;
        public void ResetCapBalance() => __pbn__CapBalance = null;
        private uint? __pbn__CapBalance;

        [global::ProtoBuf.ProtoMember(5, Name = @"startup_period")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float StartupPeriod
        {
            get => __pbn__StartupPeriod ?? 0f;
            set => __pbn__StartupPeriod = value;
        }
        public bool ShouldSerializeStartupPeriod() => __pbn__StartupPeriod != null;
        public void ResetStartupPeriod() => __pbn__StartupPeriod = null;
        private float? __pbn__StartupPeriod;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProtocolAlias : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"server_service_name", IsRequired = true)]
        public string ServerServiceName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_service_name", IsRequired = true)]
        public string ClientServiceName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServiceAliases : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"protocol_alias")]
        public global::System.Collections.Generic.List<ProtocolAlias> ProtocolAlias { get; } = new global::System.Collections.Generic.List<ProtocolAlias>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
