// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: semantic_version.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SemanticVersion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"major_version")]
        public uint MajorVersion
        {
            get => __pbn__MajorVersion.GetValueOrDefault();
            set => __pbn__MajorVersion = value;
        }
        public bool ShouldSerializeMajorVersion() => __pbn__MajorVersion != null;
        public void ResetMajorVersion() => __pbn__MajorVersion = null;
        private uint? __pbn__MajorVersion;

        [global::ProtoBuf.ProtoMember(2, Name = @"minor_version")]
        public uint MinorVersion
        {
            get => __pbn__MinorVersion.GetValueOrDefault();
            set => __pbn__MinorVersion = value;
        }
        public bool ShouldSerializeMinorVersion() => __pbn__MinorVersion != null;
        public void ResetMinorVersion() => __pbn__MinorVersion = null;
        private uint? __pbn__MinorVersion;

        [global::ProtoBuf.ProtoMember(3, Name = @"patch_version")]
        public uint PatchVersion
        {
            get => __pbn__PatchVersion.GetValueOrDefault();
            set => __pbn__PatchVersion = value;
        }
        public bool ShouldSerializePatchVersion() => __pbn__PatchVersion != null;
        public void ResetPatchVersion() => __pbn__PatchVersion = null;
        private uint? __pbn__PatchVersion;

        [global::ProtoBuf.ProtoMember(4, Name = @"version_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionString
        {
            get => __pbn__VersionString ?? "";
            set => __pbn__VersionString = value;
        }
        public bool ShouldSerializeVersionString() => __pbn__VersionString != null;
        public void ResetVersionString() => __pbn__VersionString = null;
        private string __pbn__VersionString;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
