// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: session_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.session.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateSessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Platform
        {
            get => __pbn__Platform.GetValueOrDefault();
            set => __pbn__Platform = value;
        }
        public bool ShouldSerializePlatform() => __pbn__Platform != null;
        public void ResetPlatform() => __pbn__Platform = null;
        private uint? __pbn__Platform;

        [global::ProtoBuf.ProtoMember(3, Name = @"locale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Locale
        {
            get => __pbn__Locale.GetValueOrDefault();
            set => __pbn__Locale = value;
        }
        public bool ShouldSerializeLocale() => __pbn__Locale != null;
        public void ResetLocale() => __pbn__Locale = null;
        private uint? __pbn__Locale;

        [global::ProtoBuf.ProtoMember(4, Name = @"client_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientAddress
        {
            get => __pbn__ClientAddress ?? "";
            set => __pbn__ClientAddress = value;
        }
        public bool ShouldSerializeClientAddress() => __pbn__ClientAddress != null;
        public void ResetClientAddress() => __pbn__ClientAddress = null;
        private string __pbn__ClientAddress;

        [global::ProtoBuf.ProtoMember(5, Name = @"application_version")]
        public int ApplicationVersion
        {
            get => __pbn__ApplicationVersion.GetValueOrDefault();
            set => __pbn__ApplicationVersion = value;
        }
        public bool ShouldSerializeApplicationVersion() => __pbn__ApplicationVersion != null;
        public void ResetApplicationVersion() => __pbn__ApplicationVersion = null;
        private int? __pbn__ApplicationVersion;

        [global::ProtoBuf.ProtoMember(6, Name = @"user_agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserAgent
        {
            get => __pbn__UserAgent ?? "";
            set => __pbn__UserAgent = value;
        }
        public bool ShouldSerializeUserAgent() => __pbn__UserAgent != null;
        public void ResetUserAgent() => __pbn__UserAgent = null;
        private string __pbn__UserAgent;

        [global::ProtoBuf.ProtoMember(7, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

        [global::ProtoBuf.ProtoMember(8, Name = @"options")]
        public SessionOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"requires_mark_alive")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool RequiresMarkAlive
        {
            get => __pbn__RequiresMarkAlive ?? false;
            set => __pbn__RequiresMarkAlive = value;
        }
        public bool ShouldSerializeRequiresMarkAlive() => __pbn__RequiresMarkAlive != null;
        public void ResetRequiresMarkAlive() => __pbn__RequiresMarkAlive = null;
        private bool? __pbn__RequiresMarkAlive;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateSessionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateSessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public SessionOptions Options { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroySessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionCapacityRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionCapacityResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sessions_available")]
        public uint SessionsAvailable
        {
            get => __pbn__SessionsAvailable.GetValueOrDefault();
            set => __pbn__SessionsAvailable = value;
        }
        public bool ShouldSerializeSessionsAvailable() => __pbn__SessionsAvailable != null;
        public void ResetSessionsAvailable() => __pbn__SessionsAvailable = null;
        private uint? __pbn__SessionsAvailable;

        [global::ProtoBuf.ProtoMember(2, Name = @"time_frame_seconds")]
        public uint TimeFrameSeconds
        {
            get => __pbn__TimeFrameSeconds.GetValueOrDefault();
            set => __pbn__TimeFrameSeconds = value;
        }
        public bool ShouldSerializeTimeFrameSeconds() => __pbn__TimeFrameSeconds != null;
        public void ResetTimeFrameSeconds() => __pbn__TimeFrameSeconds = null;
        private uint? __pbn__TimeFrameSeconds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateByBenefactorRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"benefactor_handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle BenefactorHandle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"include_billing_disabled")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IncludeBillingDisabled
        {
            get => __pbn__IncludeBillingDisabled ?? false;
            set => __pbn__IncludeBillingDisabled = value;
        }
        public bool ShouldSerializeIncludeBillingDisabled() => __pbn__IncludeBillingDisabled != null;
        public void ResetIncludeBillingDisabled() => __pbn__IncludeBillingDisabled = null;
        private bool? __pbn__IncludeBillingDisabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateByBenefactorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"benefactor_handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle BenefactorHandle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session")]
        public global::System.Collections.Generic.List<SessionState> Sessions { get; } = new global::System.Collections.Generic.List<SessionState>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkSessionsAliveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public global::System.Collections.Generic.List<SessionIdentifier> Sessions { get; } = new global::System.Collections.Generic.List<SessionIdentifier>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkSessionsAliveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"failed_session")]
        public global::System.Collections.Generic.List<SessionIdentifier> FailedSessions { get; } = new global::System.Collections.Generic.List<SessionIdentifier>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"include_billing_disabled")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IncludeBillingDisabled
        {
            get => __pbn__IncludeBillingDisabled ?? false;
            set => __pbn__IncludeBillingDisabled = value;
        }
        public bool ShouldSerializeIncludeBillingDisabled() => __pbn__IncludeBillingDisabled != null;
        public void ResetIncludeBillingDisabled() => __pbn__IncludeBillingDisabled = null;
        private bool? __pbn__IncludeBillingDisabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session")]
        public SessionState Session { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSignedSessionStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSignedSessionStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get => __pbn__Token ?? "";
            set => __pbn__Token = value;
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RefreshSessionKeyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RefreshSessionKeyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionCreatedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionDestroyedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionUpdatedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
