// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: session_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.session.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateSessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Platform
        {
            get => __pbn__Platform.GetValueOrDefault();
            set => __pbn__Platform = value;
        }
        public bool ShouldSerializePlatform() => __pbn__Platform != null;
        public void ResetPlatform() => __pbn__Platform = null;
        private uint? __pbn__Platform;

        [global::ProtoBuf.ProtoMember(3, Name = @"locale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Locale
        {
            get => __pbn__Locale.GetValueOrDefault();
            set => __pbn__Locale = value;
        }
        public bool ShouldSerializeLocale() => __pbn__Locale != null;
        public void ResetLocale() => __pbn__Locale = null;
        private uint? __pbn__Locale;

        [global::ProtoBuf.ProtoMember(4, Name = @"client_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientAddress
        {
            get => __pbn__ClientAddress ?? "";
            set => __pbn__ClientAddress = value;
        }
        public bool ShouldSerializeClientAddress() => __pbn__ClientAddress != null;
        public void ResetClientAddress() => __pbn__ClientAddress = null;
        private string __pbn__ClientAddress;

        [global::ProtoBuf.ProtoMember(5, Name = @"application_version")]
        public int ApplicationVersion
        {
            get => __pbn__ApplicationVersion.GetValueOrDefault();
            set => __pbn__ApplicationVersion = value;
        }
        public bool ShouldSerializeApplicationVersion() => __pbn__ApplicationVersion != null;
        public void ResetApplicationVersion() => __pbn__ApplicationVersion = null;
        private int? __pbn__ApplicationVersion;

        [global::ProtoBuf.ProtoMember(6, Name = @"user_agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserAgent
        {
            get => __pbn__UserAgent ?? "";
            set => __pbn__UserAgent = value;
        }
        public bool ShouldSerializeUserAgent() => __pbn__UserAgent != null;
        public void ResetUserAgent() => __pbn__UserAgent = null;
        private string __pbn__UserAgent;

        [global::ProtoBuf.ProtoMember(7, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

        [global::ProtoBuf.ProtoMember(8, Name = @"options")]
        public SessionOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"requires_mark_alive")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool RequiresMarkAlive
        {
            get => __pbn__RequiresMarkAlive ?? false;
            set => __pbn__RequiresMarkAlive = value;
        }
        public bool ShouldSerializeRequiresMarkAlive() => __pbn__RequiresMarkAlive != null;
        public void ResetRequiresMarkAlive() => __pbn__RequiresMarkAlive = null;
        private bool? __pbn__RequiresMarkAlive;

        [global::ProtoBuf.ProtoMember(10, Name = @"mac_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MacAddress
        {
            get => __pbn__MacAddress ?? "";
            set => __pbn__MacAddress = value;
        }
        public bool ShouldSerializeMacAddress() => __pbn__MacAddress != null;
        public void ResetMacAddress() => __pbn__MacAddress = null;
        private string __pbn__MacAddress;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateSessionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

        [global::ProtoBuf.ProtoMember(2, Name = @"timeout_s")]
        public uint TimeoutS
        {
            get => __pbn__TimeoutS.GetValueOrDefault();
            set => __pbn__TimeoutS = value;
        }
        public bool ShouldSerializeTimeoutS() => __pbn__TimeoutS != null;
        public void ResetTimeoutS() => __pbn__TimeoutS = null;
        private uint? __pbn__TimeoutS;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateSessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"options")]
        public SessionOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DestroySessionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateByBenefactorRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"benefactor_handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle BenefactorHandle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"include_billing_disabled")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IncludeBillingDisabled
        {
            get => __pbn__IncludeBillingDisabled ?? false;
            set => __pbn__IncludeBillingDisabled = value;
        }
        public bool ShouldSerializeIncludeBillingDisabled() => __pbn__IncludeBillingDisabled != null;
        public void ResetIncludeBillingDisabled() => __pbn__IncludeBillingDisabled = null;
        private bool? __pbn__IncludeBillingDisabled;

        [global::ProtoBuf.ProtoMember(3, Name = @"benefactor_uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BenefactorUuid
        {
            get => __pbn__BenefactorUuid ?? "";
            set => __pbn__BenefactorUuid = value;
        }
        public bool ShouldSerializeBenefactorUuid() => __pbn__BenefactorUuid != null;
        public void ResetBenefactorUuid() => __pbn__BenefactorUuid = null;
        private string __pbn__BenefactorUuid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateByBenefactorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"benefactor_handle")]
        [global::System.Obsolete]
        public global::bgs.protocol.account.v1.GameAccountHandle BenefactorHandle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session")]
        public global::System.Collections.Generic.List<SessionState> Sessions { get; } = new global::System.Collections.Generic.List<SessionState>();

        [global::ProtoBuf.ProtoMember(3, Name = @"minutes_remaining")]
        public uint MinutesRemaining
        {
            get => __pbn__MinutesRemaining.GetValueOrDefault();
            set => __pbn__MinutesRemaining = value;
        }
        public bool ShouldSerializeMinutesRemaining() => __pbn__MinutesRemaining != null;
        public void ResetMinutesRemaining() => __pbn__MinutesRemaining = null;
        private uint? __pbn__MinutesRemaining;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkSessionsAliveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public global::System.Collections.Generic.List<SessionIdentifier> Sessions { get; } = new global::System.Collections.Generic.List<SessionIdentifier>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkSessionsAliveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"failed_session")]
        public global::System.Collections.Generic.List<SessionIdentifier> FailedSessions { get; } = new global::System.Collections.Generic.List<SessionIdentifier>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"include_billing_disabled")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IncludeBillingDisabled
        {
            get => __pbn__IncludeBillingDisabled ?? false;
            set => __pbn__IncludeBillingDisabled = value;
        }
        public bool ShouldSerializeIncludeBillingDisabled() => __pbn__IncludeBillingDisabled != null;
        public void ResetIncludeBillingDisabled() => __pbn__IncludeBillingDisabled = null;
        private bool? __pbn__IncludeBillingDisabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        [global::System.Obsolete]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session")]
        public SessionState Session { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSignedSessionStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent_id")]
        public global::bgs.protocol.account.v1.GameAccountHandle AgentId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSignedSessionStateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get => __pbn__Token ?? "";
            set => __pbn__Token = value;
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RefreshSessionKeyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RefreshSessionKeyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetGameSessionInfoRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetGameSessionInfoResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_info")]
        public GameSessionInfo SessionInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionCreatedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

        [global::ProtoBuf.ProtoMember(4, Name = @"session_key")]
        public byte[] SessionKey
        {
            get => __pbn__SessionKey;
            set => __pbn__SessionKey = value;
        }
        public bool ShouldSerializeSessionKey() => __pbn__SessionKey != null;
        public void ResetSessionKey() => __pbn__SessionKey = null;
        private byte[] __pbn__SessionKey;

        [global::ProtoBuf.ProtoMember(5, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get => __pbn__ClientId ?? "";
            set => __pbn__ClientId = value;
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionDestroyedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionUpdatedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(3, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionGameTimeWarningNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

        [global::ProtoBuf.ProtoMember(3, Name = @"remaining_time_duration_min")]
        public uint RemainingTimeDurationMin
        {
            get => __pbn__RemainingTimeDurationMin.GetValueOrDefault();
            set => __pbn__RemainingTimeDurationMin = value;
        }
        public bool ShouldSerializeRemainingTimeDurationMin() => __pbn__RemainingTimeDurationMin != null;
        public void ResetRemainingTimeDurationMin() => __pbn__RemainingTimeDurationMin = null;
        private uint? __pbn__RemainingTimeDurationMin;

        [global::ProtoBuf.ProtoMember(4, Name = @"restriction_type")]
        public uint RestrictionType
        {
            get => __pbn__RestrictionType.GetValueOrDefault();
            set => __pbn__RestrictionType = value;
        }
        public bool ShouldSerializeRestrictionType() => __pbn__RestrictionType != null;
        public void ResetRestrictionType() => __pbn__RestrictionType = null;
        private uint? __pbn__RestrictionType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionQueueUpdatedNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

        [global::ProtoBuf.ProtoMember(3, Name = @"position")]
        public uint Position
        {
            get => __pbn__Position.GetValueOrDefault();
            set => __pbn__Position = value;
        }
        public bool ShouldSerializePosition() => __pbn__Position != null;
        public void ResetPosition() => __pbn__Position = null;
        private uint? __pbn__Position;

        [global::ProtoBuf.ProtoMember(4, Name = @"avg_creation_time_ms")]
        public ulong AvgCreationTimeMs
        {
            get => __pbn__AvgCreationTimeMs.GetValueOrDefault();
            set => __pbn__AvgCreationTimeMs = value;
        }
        public bool ShouldSerializeAvgCreationTimeMs() => __pbn__AvgCreationTimeMs != null;
        public void ResetAvgCreationTimeMs() => __pbn__AvgCreationTimeMs = null;
        private ulong? __pbn__AvgCreationTimeMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionQueueEndNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity")]
        public global::bgs.protocol.account.v1.Identity Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

        [global::ProtoBuf.ProtoMember(3, Name = @"reason")]
        public uint Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
