// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: session_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.session.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"billing")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool Billing
        {
            get => __pbn__Billing ?? true;
            set => __pbn__Billing = value;
        }
        public bool ShouldSerializeBilling() => __pbn__Billing != null;
        public void ResetBilling() => __pbn__Billing = null;
        private bool? __pbn__Billing;

        [global::ProtoBuf.ProtoMember(2, Name = @"presence")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool Presence
        {
            get => __pbn__Presence ?? true;
            set => __pbn__Presence = value;
        }
        public bool ShouldSerializePresence() => __pbn__Presence != null;
        public void ResetPresence() => __pbn__Presence = null;
        private bool? __pbn__Presence;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"handle")]
        public global::bgs.protocol.account.v1.GameAccountHandle Handle { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientAddress
        {
            get => __pbn__ClientAddress ?? "";
            set => __pbn__ClientAddress = value;
        }
        public bool ShouldSerializeClientAddress() => __pbn__ClientAddress != null;
        public void ResetClientAddress() => __pbn__ClientAddress = null;
        private string __pbn__ClientAddress;

        [global::ProtoBuf.ProtoMember(3, Name = @"last_tick_time")]
        public ulong LastTickTime
        {
            get => __pbn__LastTickTime.GetValueOrDefault();
            set => __pbn__LastTickTime = value;
        }
        public bool ShouldSerializeLastTickTime() => __pbn__LastTickTime != null;
        public void ResetLastTickTime() => __pbn__LastTickTime = null;
        private ulong? __pbn__LastTickTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"create_time")]
        public ulong CreateTime
        {
            get => __pbn__CreateTime.GetValueOrDefault();
            set => __pbn__CreateTime = value;
        }
        public bool ShouldSerializeCreateTime() => __pbn__CreateTime != null;
        public void ResetCreateTime() => __pbn__CreateTime = null;
        private ulong? __pbn__CreateTime;

        [global::ProtoBuf.ProtoMember(5, Name = @"parental_controls_active")]
        public bool ParentalControlsActive
        {
            get => __pbn__ParentalControlsActive.GetValueOrDefault();
            set => __pbn__ParentalControlsActive = value;
        }
        public bool ShouldSerializeParentalControlsActive() => __pbn__ParentalControlsActive != null;
        public void ResetParentalControlsActive() => __pbn__ParentalControlsActive = null;
        private bool? __pbn__ParentalControlsActive;

        [global::ProtoBuf.ProtoMember(6, Name = @"location")]
        public global::bgs.protocol.account.v1.GameSessionLocation Location { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"using_igr_address")]
        public bool UsingIgrAddress
        {
            get => __pbn__UsingIgrAddress.GetValueOrDefault();
            set => __pbn__UsingIgrAddress = value;
        }
        public bool ShouldSerializeUsingIgrAddress() => __pbn__UsingIgrAddress != null;
        public void ResetUsingIgrAddress() => __pbn__UsingIgrAddress = null;
        private bool? __pbn__UsingIgrAddress;

        [global::ProtoBuf.ProtoMember(8, Name = @"has_benefactor")]
        public bool HasBenefactor
        {
            get => __pbn__HasBenefactor.GetValueOrDefault();
            set => __pbn__HasBenefactor = value;
        }
        public bool ShouldSerializeHasBenefactor() => __pbn__HasBenefactor != null;
        public void ResetHasBenefactor() => __pbn__HasBenefactor = null;
        private bool? __pbn__HasBenefactor;

        [global::ProtoBuf.ProtoMember(9, Name = @"igr_id")]
        public global::bgs.protocol.account.v1.IgrId IgrId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SessionIdentifier : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_account")]
        public global::bgs.protocol.account.v1.GameAccountHandle GameAccount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId
        {
            get => __pbn__SessionId ?? "";
            set => __pbn__SessionId = value;
        }
        public bool ShouldSerializeSessionId() => __pbn__SessionId != null;
        public void ResetSessionId() => __pbn__SessionId = null;
        private string __pbn__SessionId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
