// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: user_manager_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.usermanager.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RecentPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public global::bgs.protocol.EntityId EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"program")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Program
        {
            get => __pbn__Program ?? "";
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private string __pbn__Program;

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp_played", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimestampPlayed
        {
            get => __pbn__TimestampPlayed.GetValueOrDefault();
            set => __pbn__TimestampPlayed = value;
        }
        public bool ShouldSerializeTimestampPlayed() => __pbn__TimestampPlayed != null;
        public void ResetTimestampPlayed() => __pbn__TimestampPlayed = null;
        private ulong? __pbn__TimestampPlayed;

        [global::ProtoBuf.ProtoMember(4, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::bgs.protocol.Attribute> Attributes { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.Attribute>();

        [global::ProtoBuf.ProtoMember(6, Name = @"counter", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Counter
        {
            get => __pbn__Counter ?? 0u;
            set => __pbn__Counter = value;
        }
        public bool ShouldSerializeCounter() => __pbn__Counter != null;
        public void ResetCounter() => __pbn__Counter = null;
        private uint? __pbn__Counter;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockedPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id", IsRequired = true)]
        public global::bgs.protocol.EntityId AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BattleTag
        {
            get => __pbn__BattleTag ?? "";
            set => __pbn__BattleTag = value;
        }
        public bool ShouldSerializeBattleTag() => __pbn__BattleTag != null;
        public void ResetBattleTag() => __pbn__BattleTag = null;
        private string __pbn__BattleTag;

        [global::ProtoBuf.ProtoMember(3, Name = @"role")]
        [global::System.Obsolete]
        public uint[] Roles { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"privileges")]
        [global::System.Obsolete]
        public ulong Privileges
        {
            get => __pbn__Privileges.GetValueOrDefault();
            set => __pbn__Privileges = value;
        }
        public bool ShouldSerializePrivileges() => __pbn__Privileges != null;
        public void ResetPrivileges() => __pbn__Privileges = null;
        private ulong? __pbn__Privileges;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
