// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: whisper_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.whisper.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Whisper : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_id")]
        public global::bgs.protocol.account.v1.AccountId SenderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"recipient_id")]
        public global::bgs.protocol.account.v1.AccountId RecipientId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

        [global::ProtoBuf.ProtoMember(6, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(7, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ViewMarker : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_id")]
        public global::bgs.protocol.account.v1.AccountId SenderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_read_time")]
        public ulong LastReadTime
        {
            get => __pbn__LastReadTime.GetValueOrDefault();
            set => __pbn__LastReadTime = value;
        }
        public bool ShouldSerializeLastReadTime() => __pbn__LastReadTime != null;
        public void ResetLastReadTime() => __pbn__LastReadTime = null;
        private ulong? __pbn__LastReadTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"last_message_time")]
        public ulong LastMessageTime
        {
            get => __pbn__LastMessageTime.GetValueOrDefault();
            set => __pbn__LastMessageTime = value;
        }
        public bool ShouldSerializeLastMessageTime() => __pbn__LastMessageTime != null;
        public void ResetLastMessageTime() => __pbn__LastMessageTime = null;
        private ulong? __pbn__LastMessageTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_id")]
        public global::bgs.protocol.account.v1.AccountId TargetId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fetch_from")]
        public ulong FetchFrom
        {
            get => __pbn__FetchFrom.GetValueOrDefault();
            set => __pbn__FetchFrom = value;
        }
        public bool ShouldSerializeFetchFrom() => __pbn__FetchFrom != null;
        public void ResetFetchFrom() => __pbn__FetchFrom = null;
        private ulong? __pbn__FetchFrom;

        [global::ProtoBuf.ProtoMember(2, Name = @"fetch_until")]
        public ulong FetchUntil
        {
            get => __pbn__FetchUntil.GetValueOrDefault();
            set => __pbn__FetchUntil = value;
        }
        public bool ShouldSerializeFetchUntil() => __pbn__FetchUntil != null;
        public void ResetFetchUntil() => __pbn__FetchUntil = null;
        private ulong? __pbn__FetchUntil;

        [global::ProtoBuf.ProtoMember(3, Name = @"max_messages")]
        public uint MaxMessages
        {
            get => __pbn__MaxMessages.GetValueOrDefault();
            set => __pbn__MaxMessages = value;
        }
        public bool ShouldSerializeMaxMessages() => __pbn__MaxMessages != null;
        public void ResetMaxMessages() => __pbn__MaxMessages = null;
        private uint? __pbn__MaxMessages;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
