// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: whisper_types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.whisper.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Whisper : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_id")]
        public global::bgs.protocol.account.v1.AccountId SenderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"recipient_id")]
        public global::bgs.protocol.account.v1.AccountId RecipientId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

        [global::ProtoBuf.ProtoMember(4, Name = @"embed")]
        public global::System.Collections.Generic.List<global::bgs.protocol.EmbedInfo> Embeds { get; } = new global::System.Collections.Generic.List<global::bgs.protocol.EmbedInfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"creation_time")]
        public ulong CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private ulong? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(7, Name = @"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Program
        {
            get => __pbn__Program.GetValueOrDefault();
            set => __pbn__Program = value;
        }
        public bool ShouldSerializeProgram() => __pbn__Program != null;
        public void ResetProgram() => __pbn__Program = null;
        private uint? __pbn__Program;

        [global::ProtoBuf.ProtoMember(8, Name = @"message_id")]
        public global::bgs.protocol.MessageId MessageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WhisperView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_id")]
        public global::bgs.protocol.account.v1.AccountId SenderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"view_marker")]
        public global::bgs.protocol.ViewMarker ViewMarker { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"sender_battle_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderBattleTag
        {
            get => __pbn__SenderBattleTag ?? "";
            set => __pbn__SenderBattleTag = value;
        }
        public bool ShouldSerializeSenderBattleTag() => __pbn__SenderBattleTag != null;
        public void ResetSenderBattleTag() => __pbn__SenderBattleTag = null;
        private string __pbn__SenderBattleTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_id")]
        public global::bgs.protocol.account.v1.AccountId TargetId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
