// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: field_options.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BGSFieldOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"log")]
        [global::System.ComponentModel.DefaultValue(LogOption.Hidden)]
        public LogOption Log
        {
            get => __pbn__Log ?? LogOption.Hidden;
            set => __pbn__Log = value;
        }
        public bool ShouldSerializeLog() => __pbn__Log != null;
        public void ResetLog() => __pbn__Log = null;
        private LogOption? __pbn__Log;

        [global::ProtoBuf.ProtoMember(2, Name = @"shard_key")]
        public bool ShardKey
        {
            get => __pbn__ShardKey.GetValueOrDefault();
            set => __pbn__ShardKey = value;
        }
        public bool ShouldSerializeShardKey() => __pbn__ShardKey != null;
        public void ResetShardKey() => __pbn__ShardKey = null;
        private bool? __pbn__ShardKey;

        [global::ProtoBuf.ProtoMember(3, Name = @"fanout_key")]
        public bool FanoutKey
        {
            get => __pbn__FanoutKey.GetValueOrDefault();
            set => __pbn__FanoutKey = value;
        }
        public bool ShouldSerializeFanoutKey() => __pbn__FanoutKey != null;
        public void ResetFanoutKey() => __pbn__FanoutKey = null;
        private bool? __pbn__FanoutKey;

        [global::ProtoBuf.ProtoMember(4, Name = @"client_instance_key")]
        public bool ClientInstanceKey
        {
            get => __pbn__ClientInstanceKey.GetValueOrDefault();
            set => __pbn__ClientInstanceKey = value;
        }
        public bool ShouldSerializeClientInstanceKey() => __pbn__ClientInstanceKey != null;
        public void ResetClientInstanceKey() => __pbn__ClientInstanceKey = null;
        private bool? __pbn__ClientInstanceKey;

        [global::ProtoBuf.ProtoMember(5, Name = @"realized_enum")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RealizedEnum
        {
            get => __pbn__RealizedEnum ?? "";
            set => __pbn__RealizedEnum = value;
        }
        public bool ShouldSerializeRealizedEnum() => __pbn__RealizedEnum != null;
        public void ResetRealizedEnum() => __pbn__RealizedEnum = null;
        private string __pbn__RealizedEnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signed")]
        public SignedFieldRestriction Signed
        {
            get => __pbn__type.Is(1) ? ((SignedFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeSigned() => __pbn__type.Is(1);
        public void ResetSigned() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"unsigned")]
        public UnsignedFieldRestriction Unsigned
        {
            get => __pbn__type.Is(2) ? ((UnsignedFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeUnsigned() => __pbn__type.Is(2);
        public void ResetUnsigned() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"float")]
        public FloatFieldRestriction Float
        {
            get => __pbn__type.Is(3) ? ((FloatFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeFloat() => __pbn__type.Is(3);
        public void ResetFloat() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"string")]
        public StringFieldRestriction String
        {
            get => __pbn__type.Is(4) ? ((StringFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeString() => __pbn__type.Is(4);
        public void ResetString() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"repeated")]
        public RepeatedFieldRestriction Repeated
        {
            get => __pbn__type.Is(5) ? ((RepeatedFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeRepeated() => __pbn__type.Is(5);
        public void ResetRepeated() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"message")]
        public MessageFieldRestriction Message
        {
            get => __pbn__type.Is(6) ? ((MessageFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeMessage() => __pbn__type.Is(6);
        public void ResetMessage() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"entity_id")]
        public EntityIdRestriction EntityId
        {
            get => __pbn__type.Is(7) ? ((EntityIdRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeEntityId() => __pbn__type.Is(7);
        public void ResetEntityId() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"bytes")]
        public StringFieldRestriction Bytes
        {
            get => __pbn__type.Is(8) ? ((StringFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeBytes() => __pbn__type.Is(8);
        public void ResetBytes() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 8);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RepeatedFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"size")]
        public UnsignedIntRange Size { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"unique")]
        public bool Unique
        {
            get => __pbn__Unique.GetValueOrDefault();
            set => __pbn__Unique = value;
        }
        public bool ShouldSerializeUnique() => __pbn__Unique != null;
        public void ResetUnique() => __pbn__Unique = null;
        private bool? __pbn__Unique;

        [global::ProtoBuf.ProtoMember(3, Name = @"signed")]
        public SignedFieldRestriction Signed
        {
            get => __pbn__type.Is(3) ? ((SignedFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeSigned() => __pbn__type.Is(3);
        public void ResetSigned() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__type;

        [global::ProtoBuf.ProtoMember(4, Name = @"unsigned")]
        public UnsignedFieldRestriction Unsigned
        {
            get => __pbn__type.Is(4) ? ((UnsignedFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeUnsigned() => __pbn__type.Is(4);
        public void ResetUnsigned() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"float")]
        public FloatFieldRestriction Float
        {
            get => __pbn__type.Is(5) ? ((FloatFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeFloat() => __pbn__type.Is(5);
        public void ResetFloat() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"string")]
        public StringFieldRestriction String
        {
            get => __pbn__type.Is(6) ? ((StringFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeString() => __pbn__type.Is(6);
        public void ResetString() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"entity_id")]
        public EntityIdRestriction EntityId
        {
            get => __pbn__type.Is(7) ? ((EntityIdRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeEntityId() => __pbn__type.Is(7);
        public void ResetEntityId() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"bytes")]
        public StringFieldRestriction Bytes
        {
            get => __pbn__type.Is(8) ? ((StringFieldRestriction)__pbn__type.Object) : default;
            set => __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeBytes() => __pbn__type.Is(8);
        public void ResetBytes() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 8);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignedFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"limits")]
        public SignedIntRange Limits { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exclude", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long[] Excludes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsignedFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"limits")]
        public UnsignedIntRange Limits { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exclude")]
        public ulong[] Excludes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FloatFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"limits")]
        public FloatRange Limits { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exclude")]
        public float[] Excludes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StringFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"size")]
        public UnsignedIntRange Size { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exclude")]
        public global::System.Collections.Generic.List<string> Excludes { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityIdRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"needed")]
        public bool Needed
        {
            get => __pbn__Needed.GetValueOrDefault();
            set => __pbn__Needed = value;
        }
        public bool ShouldSerializeNeeded() => __pbn__Needed != null;
        public void ResetNeeded() => __pbn__Needed = null;
        private bool? __pbn__Needed;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(Kind.Any)]
        public Kind kind
        {
            get => __pbn__kind ?? Kind.Any;
            set => __pbn__kind = value;
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private Kind? __pbn__kind;

        [global::ProtoBuf.ProtoContract()]
        public enum Kind
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ANY")]
            Any = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT")]
            Account = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GAME_ACCOUNT")]
            GameAccount = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_OR_GAME_ACCOUNT")]
            AccountOrGameAccount = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SERVICE")]
            Service = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL")]
            Channel = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageFieldRestriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"needed")]
        public bool Needed
        {
            get => __pbn__Needed.GetValueOrDefault();
            set => __pbn__Needed = value;
        }
        public bool ShouldSerializeNeeded() => __pbn__Needed != null;
        public void ResetNeeded() => __pbn__Needed = null;
        private bool? __pbn__Needed;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum LogOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HIDDEN")]
        Hidden = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HEX")]
        Hex = 2,
    }

    // public static partial class Extensions
    // {
    //     public static BGSFieldOptions GetFieldOptions(this global::Google.Protobuf.Reflection.FieldOptions obj)
    //         => obj == null ? default : global::ProtoBuf.Extensible.GetValue<BGSFieldOptions>(obj, 90000);
    //
    //     public static void SetFieldOptions(this global::Google.Protobuf.Reflection.FieldOptions obj, BGSFieldOptions value)
    //         => global::ProtoBuf.Extensible.AppendValue<BGSFieldOptions>(obj, 90000, value);
    //
    //     public static FieldRestriction GetValid(this global::Google.Protobuf.Reflection.FieldOptions obj)
    //         => obj == null ? default : global::ProtoBuf.Extensible.GetValue<FieldRestriction>(obj, 90001);
    //
    //     public static void SetValid(this global::Google.Protobuf.Reflection.FieldOptions obj, FieldRestriction value)
    //         => global::ProtoBuf.Extensible.AppendValue<FieldRestriction>(obj, 90001, value);
    //
    // }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
