// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: routing.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public enum ClientIdentityRoutingType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_IDENTITY_ROUTING_DISABLED")]
        ClientIdentityRoutingDisabled = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_IDENTITY_ROUTING_BATTLE_NET_ACCOUNT")]
        ClientIdentityRoutingBattleNetAccount = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_IDENTITY_ROUTING_GAME_ACCOUNT")]
        ClientIdentityRoutingGameAccount = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_IDENTITY_ROUTING_INSTANCE_ID")]
        ClientIdentityRoutingInstanceId = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
