// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: game_account_handle.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace bgs.protocol.account.v2
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GameAccountHandle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"title_id")]
        public uint TitleId
        {
            get => __pbn__TitleId.GetValueOrDefault();
            set => __pbn__TitleId = value;
        }
        public bool ShouldSerializeTitleId() => __pbn__TitleId != null;
        public void ResetTitleId() => __pbn__TitleId = null;
        private uint? __pbn__TitleId;

        [global::ProtoBuf.ProtoMember(3, Name = @"region")]
        public uint Region
        {
            get => __pbn__Region.GetValueOrDefault();
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private uint? __pbn__Region;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
